### ISSUE TITLE
setting up red5 for live steaming - instructions need update

### ISSUE THREAD

**Issue by nzimas** [kaltura/server#1011]
There appears to be a mismatch between the instructions provided at http://knowledge.kaltura.com/configuring-live-streaming-kaltura-prem-using-red5 and the actual interface on the Kaltura 9.x's test me console, which looks like this once liveSteam is chosen from the "select service" drop down:
https://www.dropbox.com/s/j0gb2it2o5vl9j6/Screenshot%202014-03-23%2018.55.47.png

**Comment by jessp01** [comment]
Hello @nzimas,

We no longer support live streaming using Red5. 
You will need to use Wowza. Please see here:
https://github.com/kaltura/media-server/blob/3.0.9/Installation.md

Red5 can still be used for web cam recording, however.

Thanks,

**Comment by jessp01** [comment]
We will also adjust http://knowledge.kaltura.com/configuring-live-streaming-kaltura-prem-using-red5 accordingly, thanks for reporting it.
