### ISSUE TITLE
OpenCalais engine - code issues

### ISSUE THREAD

**Issue by hilak** [kaltura/server#10579]
https://github.com/kaltura/server/blob/0c52f838a155552efd6cba0a1cfff466711d2154/plugins/reach/plugins/OpenCalais/batch/KReachVendorTaskOpenCalaisProcessorEngine.php#L296

@TalDubovKaltura  
1. on lines 295-297 you're essentially retrieving the same metadata object from the API 3 times for 3 separate properties. Please retrieve it only once.
2. EnableTickerExtraction and OmitOutputtingOriginalText are not named according to our naming convention, which dictates lower-camel. Please revise.

**Comment by TalDubovKaltura** [comment]
1. It's one-time query, please look on line 358. I'm using a static variable to store the result.
2. Done.(lines 16-17)

**Comment by hilak** [comment]
@TalDubovKaltura I meant the variables in the following lines:
 $EnableTickerExtraction = $this->getEnableTickerExtraction($partnerId);
$OmitOutputtingOriginalText = $this->getOmitOutputtingOriginalText($partnerId);

$EnableTickerExtraction ==> $enableTickerExtraction
$OmitOutputtingOriginalTex ==> $omitOutputtingOriginalTex

**Comment by TalDubovKaltura** [comment]
@hilak Done
