### ISSUE TITLE
Missing constant

### ISSUE THREAD

**Issue by hilak** [kaltura/server#10713]
https://github.com/kaltura/server/blob/caa37df325208fcdc5d8bbced426d6525a904c8b/plugins/reach/plugins/OpenCalais/batch/KReachVendorTaskOpenCalaisProcessorEngine.php#L106

@TalDubovKaltura  this constant is missing in OpenCalaisConstants. Probably a missed commit, please fix

**Comment by TalDubovKaltura** [comment]
[Done](https://github.com/kaltura/server/commit/6101912d725b46d9a705b1cfc2578abbd69f1f73)
