### ISSUE TITLE
Incorrect PHP open tag in galleryPartialSuccess.php

### ISSUE THREAD

**Issue by Sjord** [kaltura/server#11025]
[galleryPartialSuccess.php](https://github.com/kaltura/server/blob/Quasar-17.9.0/alpha/apps/kaltura/modules/system/templates/galleryPartialSuccess.php#L57-L58) contains:

```
<?php=  $entry->getId() . " [" . $entry->getPartnerId() . "]" .
"<br>" . $entry->getName()?></a>
```

I don't think `<?php=` is a valid open tag, in any PHP configuration. This should either be `<?=` or `<?php echo`.

**Comment by jessp01** [comment]
Closing, see https://github.com/kaltura/server/pull/11546
