### ISSUE TITLE
The kaltura admin console (user) shouldn't have user creation limit.

### ISSUE THREAD

**Issue by visomar** [kaltura/server#1163]
We are making some tests with the version IX-9.14, and we have found that only 3 admins can be created at the admin_console. When you try to create a fourth, the page only reloads and does nothing else (not even a single error message). 

This is the message that appears in the log:
2014-04-30 11:03:55 [0.001356] [127.0.0.1] [1941109940] [API] [kCoreException->__construct] ERR: exception 'kUserException' in /opt/kaltura/app/alpha/lib/model/UserLoginDataPeer.php:528

The problem is that UserLoginDataPeer.php calls "$partner->getAdminLoginUsersQuota()", which in turn invokes "BasePartner::getFromCustomData()" (BasePartner.php:3254) which tries to retrieve the value of "admin_login_users_quota" from the table "kaltura.partner". The user Admin Console (id=-2) doesn't own that property, so the function uses the default value, 3. I think this quota should only be present for publishers, not system administrators.

**Comment by jessp01** [comment]
Closing since no additional feedback was provided. Would still be happy to get a pull request.
