### ISSUE TITLE
Unicode Improperly Truncated during bulk upload - Makes XML reply not well formed

### ISSUE THREAD

**Issue by flipmcf** [kaltura/server#1812]
we just uploaded a bunch of media entries via CSV file from the KMC.
One of these entries has "Bad Content" - the Title is over 256 bytes.
The Title is also in unicode.

When the Title is truncated to 256 Bytes, the truncation happens in the middle of a unicode character.

Here's the CSV entry:

* title,description,url,contentType,category
"លទ្ធផលរបាយការណ៍ពីស្ថានភាពសិទ្ធិមនុស្សកម្ពុជាក្នុងសន្និសីទនៃអង្គការសហប្រជាជាតិ (វគ្គ បញ្ចប់)-H100114RSV3-WED","",http://url.to/thevideo.mp4,video,"Khmer>1",,,,,,,

The resulting KalturaMediaListResponse contains:

    <name>\xe1\x9e\x9b\xe1\x9e\x91\xe1\x9f\x92\xe1\x9e\x92\xe1\x9e\x95\xe1\x9e\x9b\xe1\x9e\x9a\xe1\x9e\x94\xe1\x9e\xb6\xe1\x9e\x99\xe1\x9e\x80\xe1\x9e\xb6\xe1\x9e\x9a\xe1\x9e\x8e\xe1\x9f\x8d\xe1\x9e\x96\xe1\x9e\xb8\xe1\x9e\x9f\xe1\x9f\x92\xe1\x9e\x90\xe1\x9e\xb6\xe1\x9e\x93\xe1\x9e\x97\xe1\x9e\xb6\xe1\x9e\x96\xe1\x9e\x9f\xe1\x9e\xb7\xe1\x9e\x91\xe1\x9f\x92\xe1\x9e\x92\xe1\x9e\xb7\xe1\x9e\x98\xe1\x9e\x93\xe1\x9e\xbb\xe1\x9e\x9f\xe1\x9f\x92\xe1\x9e\x9f\xe1\x9e\x80\xe1\x9e\x98\xe1\x9f\x92\xe1\x9e\x96\xe1\x9e\xbb\xe1\x9e\x87\xe1\x9e\xb6\xe1\x9e\x80\xe1\x9f\x92\xe1\x9e\x93\xe1\x9e\xbb\xe1\x9e\x84\xe1\x9e\x9f\xe1\x9e\x93\xe1\x9f\x92\xe1\x9e\x93\xe1\x9e\xb7\xe1\x9e\x9f\xe1\x9e\xb8\xe1\x9e\x91\xe1\x9e\x93\xe1\x9f\x83\xe1\x9e\xa2\xe1\x9e\x84\xe1\x9f\x92\xe1\x9e\x82\xe1\x9e\x80\xe1\x9e\xb6\xe1\x9e\x9a\xe1\x9e\x9f\xe1\x9e\xa0\xe1\x9e\x94\xe1\x9f\x92\xe1\x9e\x9a\xe1\x9e\x87\xe1\x9e\xb6\xe1\x9e\x87\xe1\x9e\xb6\xe1\x9e\x8f\xe1\x9e\xb7 (\xe1\x9e\x9c\xe1\x9e\x82\xe1\x9f\x92\xe1\x9e\x82 \xe1\x9e\x94\xe1\x9e\x89\xe1\x9f\x92\xe1</name>
</pre>

Specifically the Python API, this will cause an exception:

    File "KalturaClient/Client.py", line 290, in parsePostResult
        resultXml = minidom.parseString(postResult)
    KalturaClientException: not well-formed (invalid token)

It's because \xe1 signals a continuation character, the unicode parser (correctly) eats the '<' character as the continuation, and the XML parser is left with '/name> to parse, which results in invalid XML.

The best solution would be to a unicode-safe truncation during bulk upload operations: Don't truncate based on byte-length only - make sure a complete unicode character is left at the end of the string after truncation.

However, I can also throw a quick hack into the Python API:  utf8-decode the XML, ignore errors, and then pass that to minidom for XML parsing.

See this similar situation here: http://stackoverflow.com/questions/8719330/python-utf-8-xml-parsing-suds-removing-invalid-token/8719445

**Comment by jessp01** [comment]
Closing as the discussion continued in the pull req.
