### ISSUE TITLE
Flash player not seeking

### ISSUE THREAD

**Issue by jeansalim** [kaltura/server#1918]
Hi,

I cannot make the flash player seek/jump forward. HTML5 player does it perfectly.
Any solution for that?

Thanks in advance.

**Comment by JacopoG** [comment]
Hi,
same issue, how to solve?

Thanks

**Comment by jessp01** [comment]
We no longer actively support the Flash player, you may use it but I'm afraid no bug fixes will be made.
I strongly suggest you move to our HTML5 one.
