### ISSUE TITLE
thumbasset generate action fails when file on remote storage and no local copy exists

### ISSUE THREAD

**Issue by lelikg** [kaltura/server#1926]
When exporting to remote storage + deleting local file - trying to create a thumbnail via thumbasset generate action outputs the following error:

<?xml version="1.0" encoding="utf-8"?><xml><result><error><code>SOURCE_FILE_REMOTE</code><message>The source file is remote, no local file found</message><objectType>KalturaAPIException</objectType><args></args></error></result><executionTime>0.091269016265869</executionTime></xml>

**Comment by jessp01** [comment]
Se comment here: https://github.com/kaltura/server/pull/2037#issuecomment-69490178
