### ISSUE TITLE
Kaltura installation  problem in  centos 6.3 for cluster node using chef

### ISSUE THREAD

**Issue by indraindu** [kaltura/server#1935]
Hi all,

```
   Here am a newbie,i ve been installing kaltura ce 9.17 in which i have using following cookbooks and versions listed as follows:
```

build-essential   1.4.2
kaltura           21.0.0
line              0.5.1
mysql             4.0.20
nfs               0.5.0
ntp               1.5.5
openssl           1.1.0

```
                I ve installed using chef
                          1) kaltura front,batch and nfs in one node,
                         2) sphinx,dwh,mysql in one node
                 Also refer a following link "https://github.com/kaltura/platform-install-packages/blob/master/doc/rpm-chef-cluster-deployment.md".
           When i run a kaltura front server ip.i can able to see kaltura site,but when i click on kaltura admin login ,i cant able to login,when i enter a email id and password .It shows invalid password,but i give a correct email and password.Also for single node we run a config-all file,to give admin email and password,but for cluster node we use a base-config file.

          When i run a base-config file,it shows configuration of kaltura server succeefully.But still i cannot able to login a admin console.In admin.log it shows,permissive array in infra boot.

        Also why using batch and dwh .
```

Any help guys?

Thanks in advance,
Indu

**Comment by Juraganet** [comment]
Hello,
I'm another newbie too in Kaltura, trying to deploy Kaltura cluster in my lab computers. My biggest question when doing /kaltura-$ROLE-config.sh on each nodes (batch, sphinx, dwh, etc), what value should be entered in:
CDN hostname:
Apache virtual hostname:
Is it the main host name (i.e main.domain.com attached to load balancer), or each node's host name (i.e batch.main.domain.com, sphinx.main.domain.com)?

Thanks in advance.

**Comment by jessp01** [comment]
Hello,
CDN hostname - should be the load balancer unless you intend to use an actual CDN, in which case, it should be that.
Apache virtual hostname - should be the hostname of the node. It is only relevant for Front and batch machines [provided the service URL for the batch is the local host].
Service URL - should be the LB's hostname.

If you have more questions, please post them at forum.kaltura.org.

Thanks,

**Comment by Juraganet** [comment]
Hello,
Thanks for your quick reply.
I reposted this question in forum.
