### ISSUE TITLE
Captions and size issue after update

### ISSUE THREAD

**Issue by jeansalim** [kaltura/server#1953]
Hi,

-After updating to 9.19.7 captions are not showing anymore in my website although they appear fine while previewing in KMC.
-After updating to 9.19.8, when going fullscreen (KMC or embed) the video only appears on half of the screen.
-When putting the multiple playlist below the player, the playlist selection disappears. If player specified as below/horizontal, they appear again.
- On 9.19.8, On page selection is broken, playlists do not show anymore
- And I'm getting that error a lot in kaltlog : ==> /opt/kaltura/log/kaltura_apache_errors.log <==
  [Wed Dec 03 01:40:11 2014] [error] [client 10.100.9.53] PHP Fatal error:  Call to undefined function mb_detect_encoding() in /opt/kaltura/web/html5/html5lib/v2.22/simplePhpXMLProxy.php on line 271, referer: http://flomina.com/?p=62
  I investigated a bit and found that:
  [root@backend1 /]# php /opt/kaltura/web/html5/html5lib/v2.22/simplePhpXMLProxy.php
  PHP Notice:  Undefined index: SERVER_PORT in /opt/kaltura/web/html5/html5lib/v2.22/includes/DefaultSettings.php on line 29
  PHP Notice:  Undefined index: SERVER_PORT in /opt/kaltura/web/html5/html5lib/v2.22/includes/DefaultSettings.php on line 29
  PHP Notice:  Undefined index: SERVER_PORT in /opt/kaltura/web/html5/html5lib/v2.22/includes/DefaultSettings.php on line 29
  PHP Notice:  Undefined index: SERVER_NAME in /opt/kaltura/web/html5/html5lib/v2.22/includes/DefaultSettings.php on line 30
  PHP Notice:  Undefined index: HTTP_HOST in /opt/kaltura/web/html5/html5lib/v2.22/includes/DefaultSettings.php on line 166
  PHP Fatal error:  Call to undefined function mb_detect_encoding() in /opt/kaltura/web/html5/html5lib/v2.22/simplePhpXMLProxy.php on line 271
  It seems like $_SERVER['SERVER_NAME'] and SERVER_PORT do not return a value (I tested it)

Thanks a lot for your hard work.

**Comment by jessp01** [comment]
@jeansalim - can this be closed or are you still having issues? Thanks,
