### ISSUE TITLE
Kaltura deployment -nginx-vod module issue

### ISSUE THREAD

**Issue by indraindu** [kaltura/server#2171]
Hi,

         When deploying kaltura using chef,i ve installed it.But today when iam installing it shows like this:
Mixlib::ShellOut::ShellCommandFailed: execute[configure Kaltura ] (kaltura::default line 100) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1' ---- Begin output of echo NO | /opt/kaltura/bin/kaltura-config-all.sh /root/kaltura.ans ---- STDOUT: Running base config... kaltura-base-10.3.0-3.noarch u001b[0;36mWelcome to Kaltura Server 10.3.0 post install setup.u001b[m u001b[1;31mERROR: Missing the following params in /root/kaltura.ans VOD_PACKAGER_HOST VOD_PACKAGER_PORT IP_RANGE u001b[m u001b[1;31mERROR: /opt/kaltura/bin/kaltura-base-config.sh failed:( You can re-run it when the issue is fixed.u001b[m STDERR: ---- End output of echo NO | /opt/kaltura/bin/kaltura-config-all.sh /root/kaltura.ans ---- Ran echo NO | /opt/kaltura/bin/kaltura-config-all.sh /root/kaltura.ans returned 1]

    When searching it relates to nginx-vod-module,whats that?its newly added feature?
Thanks,
indu

**Comment by KalturaCommunity** [comment]
Indeed, new added feature. Chef recipe ver 24.1.0 is the latest and has 
been adjust to work with it.

More about the feature:
http://forum.kaltura.org/t/kaltura-ce-10-3-0-released/1633

Thanks,

May the source be with you,

Jess Portnoy

**Comment by indraindu** [comment]
Hi,

      Thanks,will try that.Whether its possible to download kaltura server and install it  from our local storageinstead of lconnecting internet .

THanks,
indu

**Comment by jessp01** [comment]
Possible indeed. See:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.4.0/doc/deploy-local-rpm-repo-offline-install.md

May the source be with you,

Jess Portnoy

**Comment by indraindu** [comment]
Hi,
   
      I ve change my kaltura.repo in /etc/yum.repos.d  like this:
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.kaltura.org/releases/9.19.8/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

[Kaltura-noarch]
name = Kaltura Server arch independent
baseurl = http://installrepo.kaltura.org/releases/9.19.8/RPMS/noarch
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

[Kaltura-testing]
name = Kaltura Server arch independent
baseurl = http://installrepo.kaltura.org/releases/9.19.8/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

[Kaltura-testing-noarch]
name = Kaltura Server arch independent
baseurl = http://installrepo.kaltura.org/releases/9.19.8/RPMS/noarch
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1


But when am installing kaltura server using yum -y install kaltura-server it installs 10.3.0-1 showing like this :   [root@centos-0 yum.repos.d]# yum -y install kaltura-server
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
 * base: centos.mirror.nac.net
 * epel: mirrors.mit.edu
 * extras: mirrors.tripadvisor.com
 * updates: mirror.metrocast.net
Kaltura                                                                                                                  | 2.9 kB     00:00     
Not using downloaded repomd.xml because it is older than what we have:
  Current   : Mon Jan 26 08:34:11 2015
  Downloaded: Wed Dec 10 11:32:51 2014
Kaltura-noarch                                                                                                           | 2.9 kB     00:00     
Not using downloaded repomd.xml because it is older than what we have:
  Current   : Sun Jan 25 10:10:55 2015
  Downloaded: Wed Dec 17 08:27:27 2014
Kaltura-testing                                                                                                          | 2.9 kB     00:00     
Not using downloaded repomd.xml because it is older than what we have:
  Current   : Mon Jan 26 08:34:11 2015
  Downloaded: Wed Dec 10 11:32:51 2014
Kaltura-testing-noarch                                                                                                   | 2.9 kB     00:00     
Not using downloaded repomd.xml because it is older than what we have:
  Current   : Sun Jan 25 10:10:55 2015
  Downloaded: Wed Dec 17 08:27:27 2014
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package kaltura-server.noarch 0:10.3.0-1 will be installed
--> Processing Dependency: kaltura-widgets for package: kaltura-server-10.3.0-1.noarch
--> Processing Dependency: kaltura-sphinx for package: kaltura-server-10.3.0-1.noarch
--> Processing Dependency: kaltura-red5 for package: kaltura-server-10.3.0-1.noarch
--> Processing Dependency: kaltura-nginx for package: kaltura-server-10.3.0-1.noarch
--> Processing Dependency: kaltura-html5lib for package: kaltura-server-10.3.0-1.noarch
--> Processing Dependency: kaltura-front for package: kaltura-server-10.3.0-1.noarch
--> Processing Dependency: kaltura-dwh for package: kaltura-server-10.3.0-1.noarch
--> Processing Dependency: kaltura-batch for package: kaltura-server-10.3.0-1.noarch
--> Running transaction check
---> Package kaltura-batch.noarch 0:10.3.0-1 will be installed
--> Processing Dependency: sox for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: php-pecl-ssh2 for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: php-pecl-memcached for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: php-mcrypt for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: php for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: mod_ssl for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: memcached for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: mediainfo for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: kaltura-sshpass for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: kaltura-segmenter for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: kaltura-mencoder for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: kaltura-ffmpeg-aux for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: kaltura-ffmpeg for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: kaltura-base for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: httpd for package: kaltura-batch-10.3.0-1.noarch
--> Processing Dependency: ImageMagick for package: kaltura-batch-10.3.0-1.noarch
---> Package kaltura-dwh.noarch 0:9.4.0-2 will be installed
--> Processing Dependency: kaltura-postinst for package: kaltura-dwh-9.4.0-2.noarch
--> Processing Dependency: kaltura-pentaho for package: kaltura-dwh-9.4.0-2.noarch
--> Processing Dependency: jre for package: kaltura-dwh-9.4.0-2.noarch
http://installrepo.kaltura.org/releases/9.19.8/RPMS/noarch/repodata/776a9aa6036c991fdf49e1e76925c74a14c4642998468336c274bd0c9393cbf5-filelists.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: failure: repodata/776a9aa6036c991fdf49e1e76925c74a14c4642998468336c274bd0c9393cbf5-filelists.sqlite.bz2 from Kaltura-noarch: [Errno 256] No more mirrors to try.
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest


Regards,
Indu

**Comment by indraindu** [comment]
When iam using "yum clean all "command,it gets install, why it didnot get install when downloading at first.
Thanks,
Indu
