### ISSUE TITLE
error after upgrade to 10.3 from 10.2

### ISSUE THREAD

**Issue by himbeere** [kaltura/server#2181]
Hello.

I get the following errors after upgrading to 10.2:

[root@videos ~]# /opt/kaltura/bin/kaltura-db-update.sh
Error occurred during DB update:
	 || ERROR 1091 (42000) at line 1: Can't DROP 'entry_id_index'; check that column/key exists || ERROR 1050 (42S01) at line 1: Table 'drm_policy' already exists || ERROR 1091 (42000) at line 17: Can't DROP 'profile_id'; check that column/key exists || ERROR 1060 (42S21) at line 1: Duplicate column name 'root_job_id' || ERROR 1050 (42S01) at line 1: Table 'delivery_profile' already exists
	
[root@videos ~]# /opt/kaltura/bin/kaltura-config-all.sh kaltura_15_01_19_03.ans 
Running base config...

kaltura-base-10.3.0-3.noarch
Welcome to Kaltura Server 10.3.0 post install setup.
ERROR: Missing the following params in kaltura_15_01_19_03.ans
                
VOD_PACKAGER_HOST
VOD_PACKAGER_PORT
IP_RANGE
                
ERROR: /opt/kaltura/bin/kaltura-base-config.sh failed:( You can re-run it when the issue is fixed.

best regards

**Comment by KalturaCommunity** [comment]
Hello,

The MySQL errs can be ignored. Add the 3 vars to the answer file. Host is where the kaltura-nginx is installed, same host in the case of a single server. Port can be whatever but ensure not to choose the port Apache listens on. IP_RANGE can be 0.0.0.0-255.255.255.255 to include all hosts. Revise accordingly



May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by himbeere** [comment]
Okay thanks. After adding those everything works.
