### ISSUE TITLE
Deprecated APIs: no pointers to replacements

### ISSUE THREAD

**Issue by jbiblio** [kaltura/server#2264]
Some APIs, like the whole `upload` service or the `getUsage` action of the `upload` service are marked as deprecated.

Maybe I'm searching at the wrong places, but I do not see any pointers to possible replacements of such APIs. Even the API documentation does not contain the deprecation notice for actions, only services are marked as deprecated.

The generated clients (at least the Java client) do not name the deprecation, too.

Would it be possible to add these information to the documentation?

Thanks in advance!
Regards,
Michael

**Comment by tan-tan-kanarek** [comment]
You're right Michael, the deprecation should point to replacement and should be reflected in all client libraries.
These tasks are prioritized internally and may take some time.
You're most welcome to suggest a pull-request on any of the client libraries generators and we will review it.

**Comment by jbiblio** [comment]
Thanks for your feedback, if I find some time I'll take a look into the Java client generator.

As far as I understand the generators uses the schema definition from http://www.kaltura.com/api_v3/api_schema.php. But where do I find the deprecation notices?

**Comment by tan-tan-kanarek** [comment]
The XML schema is generated from the server code doc comments:
https://github.com/kaltura/server/blob/Jupiter-10.5.0/generator/XmlClientGenerator.php
