### ISSUE TITLE
cent os control panel

### ISSUE THREAD

**Issue by tharldvs1** [kaltura/server#2270]
Will kaltura work if I install centos control panel first? I have a few domains on my server and i would like to add live streaming and video chat functionality to the different domains

**Comment by jessp01** [comment]
Hello,

What do you mean by 'centos control panel'? Also, for general questions, please post on forum.kaltura.org instead.

**Comment by tharldvs1** [comment]
Centos web panel it is a hosting control panel http://centos-webpanel.com/

**Comment by tharldvs1** [comment]
Or can I assign domain names to channels? Also I am trying to install kaltura by following the guide you have on github and I came to this error Nginx port to listen on [88]: 
Starting nginx: nginx: [emerg] host not found in upstream "server1.deviousmediaproductions.us" in /etc/nginx/nginx.conf:17
                                                           [FAILED]
ERROR: /opt/kaltura/bin/kaltura-nginx-config.sh failed:( You can re-run it when the issue is fixed.

**Comment by tharldvs1** [comment]
Oh yeah using the new 1.0.5 version of red5 requires jdk8 this too is a future problem if you can help with the above problem

**Comment by tharldvs1** [comment]
How long befor this works with red5 pro?

**Comment by jessp01** [comment]
Hello,

Nginx - I answered you here: http://forum.kaltura.org/t/error-during-install/1814/last
Red5 - it requires Java 1.7 which is also reflected in the 'Requires' tag in the RPM spec, where did you see it requiring version 8?

For general questions, please post on forum.kaltura.org, please open github issues for bug reports only.

Thanks,

**Comment by tharldvs1** [comment]
It is in documentation for red 5 1.0.5 it said the target was intended to be 7 but you have to use 8 for 1.0.5 I am currently testing the new red5pro. I think you will be able to disregard my origional question because there is a better solution in the new red5pro. Thanks for responding!
