### ISSUE TITLE
Composer: Kaltura via Packagist

### ISSUE THREAD

**Issue by KLVTZ** [kaltura/server#2275]
Proposal
------------
> Jupiter-10.5.0-PHP53-Client-Composer-Support

Would love to re-build the base PHP-53 generated API client in similar fashion to what I have as an example: [kaltura-client53](https://github.com/KLVTZ/kaltura-client53).

This would encourage PSR-4, which proceeds the now deprecated PSR-0- standard that is currently implemented in this branch. Furthermore, it would make sense to autoload this in the space of `src` as that follows best practices in other composer packages. From there, Kaltura would highly be encouraged to move this client to an official [packagist](https://packagist.org/search/?q=kaltura) release for others to implement.

To-Do
---------
zoharbabin informed that I should work on this repo, under the composer branch. I wanted to verify what steps would need to be made in order to properly PR this implementation. More specifically, am I to alter the composer specific branch of `generator/sources/php53` to the current file structure as demoed above and then alter the file paths reference in `generator/Php53ClientGenerator.php`? Are these the only files to which I would be responsible for altering or are there other things I need to take into consideration?

**Comment by jessp01** [comment]
Hello,

Please fork the server repo version Jupiter-10.6.0 and submit a pull request.
Also, since @rkreich also made this pull:
https://github.com/kaltura/server/tree/Jupiter-10.5.0-PHP53-Client-Composer-Support

Can you guys please sync?

Thanks a lot

**Comment by KLVTZ** [comment]
Thanks for the info. @rkreich would the above `to-do` proposal be in-line with the proper way to generate a PSR-4 compliant standard release? Do you find any other files that I would have to concern myself with?

**Comment by rkreich** [comment]
Hi @KLVTZ, 
Do you suggest on using PSR-4 in order simplify the folders structure? So `/Kaltura/Client` would be removed? Basically PSR-4 (as much as I understand) is backward compatible with PSR-0.

I would prefer to first have the end to end composer support as it requires the automatic build system that @jessp01 is maintaining to build https://github.com/kaltura/KalturaGeneratedAPIClientsPHP53 automatically and add version management using tags. Once that done, it will allow us to submit that repo to packagist.

**Comment by KLVTZ** [comment]
@rkreich Not necessarily simplifying folder structure but instead using PSR-4 because PSR-0 is now deprecated by the fig. From what I see, there is no issue leaving the folder structure as is. I just suggested the `src/` use as other popular frameworks follow a similar style. That would be awesome have version management and see this on pacakgist.

**Comment by rkreich** [comment]
OK, so all we need to do is change this line: https://github.com/kaltura/server/commit/69c4ea443b694a1da83b847b71645d6edb188565#diff-8cd1e18464673cd0b54be4c76f33ecdcR17 to `psr-4`. Right? 
I'll test it, but in any case, the php5.3 library should be psr-4 compatible already, because it doesn't rely on specific auto-loading mechanism.

Changing `library/` to `src/` would break backward compatibility for existing developers. 
`library/` was originally inspired by zf2, which is still kept today (https://github.com/zendframework/zf2). I actually remember naming this client library as zf2 and then changing it to php5.3 :)

**Comment by jessp01** [comment]
Hey guys,

Just wondering if there was additional progress... 

Thanks:)

**Comment by rkreich** [comment]
Hi Jess, 
We need your help regarding the auto generated library.
The generated github repository should look like in the following example:
https://github.com/rkreich/KalturaGeneratedAPIClientsPHP53
(I removed the php53 folder)
We also need to tag each release with the version number from the core repo. So when generating against final `Jupiter-10.5.0`, the `KalturaGeneratedAPIClientsPHP53` master should be tagged as `10.5.0`.
Besides that, all is left is to merge https://github.com/kaltura/server/tree/Jupiter-10.5.0-PHP53-Client-Composer-Support into next release.

**Comment by jessp01** [comment]
Hi Roman,

npc. So just to make sure I understand:
- Need to take contents out of https://github.com/kaltura/server/tree/Jupiter-$VER/generator/sources/php53 and push to https://github.com/kaltura/KalturaGeneratedAPIClientsPHP53/
directly, i.e; without having a directory called php53 inside
- create a branch for each Core release where, if the Core branch is 'Jupiter-10.7.0', the genlibs branch is '10.7.0'

Correct?

**Comment by rkreich** [comment]
Re #1 - The contents that goes to KalturaGeneratedAPIClientsPHP53 should be the auto-generated code (that you generate somewhere :) ), not the one taken from the server repo.
The only change that is required is discarding the php53 folder on the generated output.
Re #2 - That's correct

**Comment by KalturaCommunity** [comment]
Hi Roman,

Yes, I meant the generated result of the php53 server dir should go 
directly under KalturaGeneratedAPIClientsPHP53:)

I am testing it right now and will let you know.
We should do the same with the PHP5 and ZF repos. Can you handle that?

May the source be with you,

Jess Portnoy

**Comment by rkreich** [comment]
I don't think that this is required, Composer endorse php5.3+ standards, php5 and zf1 are treated legacy in the Composer world.

**Comment by jessp01** [comment]
OK, I agree. Made the modifications and you can see:
https://travis-ci.org/kaltura/KalturaGeneratedAPIClientsPHP53
Now has branch 10.7.0 and is green.

Feel free to merge you pull and then I can run the whole cycle and test 
against 10.8.0.

May the source be with you,

Jess Portnoy

**Comment by jessp01** [comment]
@KLVTZ, just to update you, the push to packagist is now done automatically.
@rkreich and I tested it yesterday. Thank you for your part in it:)

**Comment by zoharbabin** [comment]
@jessp01 sweet!

**Comment by KLVTZ** [comment]
@jessp01 @rkreich sweet! Thank you both for carrying this out. Super awesome to have this available in a project via composer.

**Comment by jessp01** [comment]
Our pleasure, Justin, glad you find it useful:)
