### ISSUE TITLE
De-escalating invalid KS messages

### ISSUE THREAD

**Issue by jpluijmers** [kaltura/server#2302]
On a production environment hosting various clients the log is filled with messages like:

[kPermissionManager::errorIfKsNotValid] ERR: exception 'Exception' with message 'KS Expired [2015-03-05 08:32:50]'

This is logged as an error including traces, and technically it is. But it clutters the log. Should we perhaps change this to E_WARNING?

**Comment by jessp01** [comment]
Hey Joost,

Yes, it makes sense. Please submit a pull request.
Thank you,
