### ISSUE TITLE
Image does not process from FTP drop if file-name is only 1 character long

### ISSUE THREAD

**Issue by iddrew** [kaltura/server#2304]
Hi,

We have noticed an issue where if you upload an image to the FTp drop but the image name has only 1 character (e.g. 9.png) Then it is not processed. anything with more than 1 character is processed.

Below is a excerpt of the api log showing A file (called 19.png) that was processed successfully and another one (called 9.png) that was not.

19.png that was processed successfully:

[service] => dropfolder_dropfolderfile
    [action] => add
    [apiVersion] => 3.1.6
    [format] => 3
    [clientTag] => batch: batch2.xx.xxxxx.com KAsyncDropFolderWatcher index: 0 sessionId: 2000985637
    [ignoreNull] => 1
    [dropFolderFile:objectType] => KalturaDropFolderFile
    [dropFolderFile:dropFolderId] => 3000003
    [dropFolderFile:fileName] => 19.png
    [dropFolderFile:fileSize] => 6685
    [dropFolderFile:lastModificationTime] => 1425382427
    [dropFolderFile:uploadStartDetectedAt] => 1425382429
    [partnerId] => 3000006
    [ks] => NTg4ODBlOGE5MDNhNWIyYjk0NzE5Nzk0NTczNTY3YWUwYzM0ODE5NXwtMTs7MTQyNzk3NDQyODsyOzE0MjUzODI0MjguMzkzNjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==    
    [kalsig] => 01bfdcaae26dd6ffdd3c32beaaa3e12e

9.png that was not processed successfully:

[service] => dropfolder_dropfolderfile
    [action] => add
    [apiVersion] => 3.1.6
    [format] => 3
    [clientTag] => batch: batch2.xx.xxxxx.com KAsyncDropFolderWatcher index: 0 sessionId: 2000985637
    [ignoreNull] => 1
    [dropFolderFile:objectType] => KalturaDropFolderFile
    [dropFolderFile:dropFolderId] => 3000003
    [dropFolderFile:fileName] => 9.png
    [dropFolderFile:fileSize] => 0
    [dropFolderFile:lastModificationTime] => 1425382428
    [dropFolderFile:uploadStartDetectedAt] => 1425382429
    [partnerId] => 3000006
    [ks] => NTg4ODBlOGE5MDNhNWIyYjk0NzE5Nzk0NTczNTY3YWUwYzM0ODE5NXwtMTs7MTQyNzk3NDQyODsyOzE0MjUzODI0MjguMzkzNjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==
    [kalsig] => 552e849539cec905dc588c4c85e181da

Notice that the 9.png that failed had  [dropFolderFile:fileSize] => 0 set to 0 while the one that processed had the correct value set.

**Comment by iddrew** [comment]
Also, notice that it stays "processing" in the kmc

![kmc1](https://cloud.githubusercontent.com/assets/3509882/6505568/cb1937a6-c343-11e4-8cd6-48e72c3501e4.png)

**Comment by jessp01** [comment]
Hello and thanks a lot for the report.
I spoke to Andrew and I understand this relates to 9.14.0. I was unable to reproduce this for 10.6.0 so I imagine it was either fixed since or happens under very specific conditions.
If you can still recreate this with 10.6.0 please reopen.
