### ISSUE TITLE
Get all playlists to which a media belongs

### ISSUE THREAD

**Issue by rohith-m** [kaltura/server#2334]
Hi I would like to retrieve all playlists to which a media entry belongs to, currently I cant find any solutions. I think this feature is a good to have if it is not already implemented as we can queue up videos in the player when a video is being played .

**Comment by tan-tan-kanarek** [comment]
You're right, currently there is no solution for that and we don't plan to implement any.
Please explain what you're trying to do and we will try to offer a different solution.

**Comment by rohith-m** [comment]
In my aplication all videos belong to some playlists, from some parts of site I am just passing video id to the player page, without any information regarding the playlist to which that particular media entry belongs to, but my application needs to queue rest of the videos in that playlist in player so that once this video is finished it is automatically moved to the next video. Right now I am using really inefficient method to do this, I will be getting all static playlists and looping through them to find playlists on which this entry belongs. This is really slow method. I wish there was certain way to pass the video id in playlist service that will return the playlists ids to which this video belongs.

**Comment by tan-tan-kanarek** [comment]
I don't know what is the business meaning of playlist in you application, but if what you need is a way to group entries statically, you could use categories and associate them with the entries. However, if you're using dynamic playlists, I don't see a meaning to "next entry" as the entry could be associated with more than one playlist.

**Comment by rohith-m** [comment]
Well to put the busienss requirements is little bit weird, it happends like this

Series        -> Thriller        -> Breaking Bad
(Category)  -> (Category) -> (Playlist)

This is how it is being organized since the application owner wants the logic to be like this.

**Comment by tan-tan-kanarek** [comment]
As said, currently it's not supported.
