### ISSUE TITLE
"Weird" progressive media streaming behaviour

### ISSUE THREAD

**Issue by jpluijmers** [kaltura/server#2385]
I'am kind of lost as to where to put this issue. I have opened a bug at Mozilla as well.

How to reproduce:
Launch Firefox 36.0.4 and open the debug tools > network
Open link http://platform.vixyvideo.com/start/0_ihi1bnx7_0_grjfkc77_2.mp4
Seek a few times and leave the player running

After a while the request frequency starts to go crazy. Only very fast connections and computers are able to keep up. 

At the suggestion of @jessp01  I have recorded the behaviour on the server side. The tcpdump cap can been downloaded at http://platform.vixyvideo.com/start/firefoxbug.cap

I have also created a screenshot displaying the behavior:  http://platform.vixyvideo.com/start/error.png

Any help would be greatly appreciated! My clients are asking to go back to flash right now!

**Comment by jessp01** [comment]
@jpluijmers - can this be closed? Thanks,

**Comment by jessp01** [comment]
Closing due to lack of response. @jpluijmers - if you are still having issues, due let us know.
