### ISSUE TITLE
Empty KMC Interface after login

### ISSUE THREAD

**Issue by rootAmeen** [kaltura/server#2408]
Hello there!

I have a weird issue with Kaltura CE installation. The installation itself went smoothly without any issue but unfortunately I wasn't able to view any interface items within KMC itself. After login all what I see is the navigation bar at the top, but nothing else.

Here's my installation Log (after dropping the db and re-configuring, assuming it could help):

===============================================================================

[root@vm-training ~]# /opt/kaltura/bin/kaltura-drop-db.sh
This will drop the following DBs:
kaltura kaltura_sphinx_log kalturadw kalturadw_ds kalturadw_bisources kalturalog
and remove users:
kaltura etl
on 127.0.0.1

NOTE: this is not reversible.
It is recommended you also back up the current data using mysqldump before continuing.
You can use /opt/kaltura/bin/kaltura-export-db.sh to export the data.

Are you absolutely certain you want this? [n/Y]

Y
root DB passwd:
Removing kaltura
Removing kaltura_sphinx_log
Removing kalturadw

Removing kalturadw_ds
Removing kalturadw_bisources
Removing kalturalog
[root@vm-training ~]#
[root@vm-training ~]#
[root@vm-training ~]# /opt/kaltura/bin/kaltura-config-all.sh
Running base config...

kaltura-base-10.8.0-14.noarch
Welcome to Kaltura Server 10.8.0 post install setup.

To keep up with the bi-weekly Kaltura releases, and stay up to date with
the latest news, security and bug updates, and connect with the global
Kaltura community - sign up for our regular Kaltura Community updates.
Please enter your email to sign up, or enter NO to pass.

[Email\NO]:NO

In order to finalize the system configuration, please input the following:

CDN hostname [vm-training.xenv.bit]:

Apache virtual hostname [vm-training.xenv.bit]
(Must be accessible from both inside the machine and from any clients / browsers that will use Kaltura):

Vhost port to listen on [80]:
range of ip addresses belonging to internal kaltura servers [0.0.0.0-255.255.255.255]:
The range is used when checking service actions permissions and allowing to access certain services without KS from the internal servers.
The default is only good for testing, on a production ENV you should adjust according to your network.

DB port [3306]:
MySQL super user [only for install, default root]:
Analytics DB hostname [127.0.0.1]:
Analytics DB port [3306]:
Sphinx hostname [127.0.0.1]:
Secondary Sphinx hostname [leave empty if none]:
VOD packager hostname [vm-training.xenv.bit]:
VOD packager port to listen on [88]:
Admin user login password (must be minimum 8 chars and include at least one of each: upper-case, lower-case, number and a special character):
Confirm passwd:
Your time zone [see http://php.net/date.timezone], or press enter for [Asia/Riyadh]:
Your Kaltura install name (this name will show as the From field in emails sent by the system) [Kaltura Video Platform]:
Your website Contact Us URL [http://corp.kaltura.com/company/contact-us]:
Your 'Contact us' phone number [+1 800 871 5224]:

========================================================================================================================
Kaltura install answer file written to /tmp/kaltura_12_04_15_43.ans  -  Please save it!
This answers file can be used to silently-install re-install this machine or deploy other hosts in your cluster.
========================================================================================================================

Configuration of 10.8.0 finished successfully!
Running FrontEnd config...

base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh

kaltura-front-10.8.0-1.noarch
Is your Apache working with SSL?[Y/n]
n
It is recommended that you do work using HTTPs. Would you like to continue anyway?[N/y]
y
Which port will this Vhost listen on? [80]

Please select one of the following options [0]:
0. All web interfaces
1. Kaltura Management Console [KMC], Hosted Apps, HTML5 lib and ClipApp
2. KAC - Kaltura Admin Console
0
Enabling Apache config - apps.conf
Enabling Apache config - var.conf
Enabling Apache config - admin.conf

========================================================================================================================
Kaltura install answer file written to /tmp/kaltura_12_04_15_44.ans  -  Please save it!
This answers file can be used to silently-install re-install this machine or deploy other hosts in your cluster.
========================================================================================================================

Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]
Shutting down monit:                                       [  OK  ]
Starting monit: Starting monit daemon with http interface at [*:2812]
                                                           [  OK  ]
Running Sphinx config...

kaltura-sphinx-2.2.1-16.x86_64
base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh

Starting monit: Starting monit daemon with http interface at [*:2812]
                                                           [  OK  ]

Configuring your Kaltura DB...

Checking MySQL version..
Ver 5.1.73 found compatible

CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log
Output for /opt/kaltura/app/deployment/base/scripts/insertPermissions.php being logged into /opt/kaltura/log/insertPermissions.log
Output for /opt/kaltura/app/deployment/base/scripts/insertContent.php being logged into /opt/kaltura/log/insertContent.log
Generating UI confs..
Shutting down monit:                                       [FAILED]
Starting monit: Starting monit daemon with http interface at [*:2812]
                                                           [  OK  ]
Running Batch config...

kaltura-batch-10.8.0-1.noarch
base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh

Reloading httpd:
Starting monit: Starting monit daemon with http interface at [*:2812]
                                                           [  OK  ]
kaltura-nginx-1.6.2-6.x86_64
Kaltura API host [vm-training.xenv.bit]:

Nginx server name [vm-training.xenv.bit]:

Nginx port to listen on [88]:
Reloading nginx:                                           [  OK  ]
Running DWH config...

kaltura-dwh-9.4.0-2.noarch
base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh

Deploying analytics warehouse DB, please be patient as this may take a while...
Output is logged to /opt/kaltura/dwh/logs/dwh_setup.log.

sending incremental file list
MySQLInserter/

sent 133 bytes  received 25 bytes  316.00 bytes/sec
total size is 2646419  speedup is 16749.49
sending incremental file list
MappingFieldRunner/

sent 147 bytes  received 25 bytes  344.00 bytes/sec
total size is 90670  speedup is 527.15
sending incremental file list
GetFTPFileNames/

sent 141 bytes  received 25 bytes  332.00 bytes/sec
total size is 7308893  speedup is 44029.48
sending incremental file list
FetchFTPFile/

sent 135 bytes  received 25 bytes  320.00 bytes/sec
total size is 5783119  speedup is 36144.49
sending incremental file list
DimLookup/

sent 126 bytes  received 25 bytes  302.00 bytes/sec
total size is 3687964  speedup is 24423.60
sending incremental file list

sent 80 bytes  received 12 bytes  184.00 bytes/sec
total size is 34770  speedup is 377.93
current version 5999
DWH configured.

====================================================================================================================

Setup completed successfully!

To access your Kaltura tools visit:
http://vm-training.xenv.bit:80

To verify the integrity of your deployment and that all components are fully configured and installed,
you can run the sanity tests using the following command:
/opt/kaltura/bin/kaltura-sanity.sh

To begin, access the Admin Console using the Admin email and password you've entered while installing.
When logged in to the KAC, create a new publisher account to being using Kaltura.
Visit http://www.kaltura.org to join the community and get help!
Visit http://forum.kaltura.org to post issues and help others with theirs.
Visit http://knowledge.kaltura.com to read documentation and learn more.
=====================================================================================================================

Thank you for running Kaltura! To keep Kaltura viable, stable and tested, please join the community and help by contributing sanity tests that verify overall platform stability: http://bit.ly/kaltura-ci , and by contributing to the project roadmap by solving simple tasks and challenges: http://bit.ly/kaltura-tasks.

==================================================

Any help would be appreciated.

**Comment by KalturaCommunity** [comment]
Hello,

I believe the issue is you have tried to login to KMC using the admin creds, please create a partner using the admin console and use it to login.


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by rootAmeen** [comment]
Thank you Jess.

When I tried to add a new publisher, I got stuck on selecting the Service Edition Type.

It's a required field, but the drop down menu shows no options, so I cannot select anything. and I get the error : "Value is required and can't be empty"

While we're at it, I also have an error on some of the pages like /admin_console/index.php/partner/list where I get the error:

"An error occurred

(error code: Server:INVALID_KS)" 

How can I fix this? 

Thanks.

**Comment by KalturaCommunity** [comment]
Hello,

Perhaps your session has expired. I suggest you relogin and try.


May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by rootAmeen** [comment]
I tried that, I even rebooted the machine but nothing solved it.

**Comment by KalturaCommunity** [comment]
run kaltlog from the shell while making the requests and lets see the 
errors you are getting..

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by jessp01** [comment]
Any update on this? Thanks,

**Comment by jessp01** [comment]
Closing due to lack of feedback. Please reopen should you have new info.
