### ISSUE TITLE
Javascript is downloaded with a weird 'image/js' content-type

### ISSUE THREAD

**Issue by rafamayoralas** [kaltura/server#2498]
I am configuring a player with a javascript external resource, as stated in http://knowledge.kaltura.com/kaltura-player-v2-toolkit-theme-skin-guide.
I upload the javascript as a document via Kaltura API through the Test Console, and configure the player in KMC Studio as an UI Variable with:
- Key: IframeCustomPluginJs1
- Value: the downloadURL value of the javascript uploaded

Despite this has been working in all browsers without issues, recently Chrome raises an error showing the following message in console:
Refused to execute script from 'http://cdnbakmi.kaltura.com/p/XXX/sp/XXX/raw/entry_id/1_xxxxxx/version/0' because its MIME type ('image/js') is not executable.
I guess it started failing since Chrome automatically upgraded to version 42.

As the message suggests, the problem arises because the javascript is downloaded with a weird 'image/js' content-type, instead of expected 'application/javascript'.
I have found that code in https://github.com/kaltura/server/blob/Jupiter-10.10.0/alpha/apps/kaltura/lib/request/infraRequestUtils.class.php does not have the javascript case in the switch in function ' sendCdnHeaders'. 
So It sets the variable $content_type as 'image/$ext', where ext is 'js', in switch default clause.

I have modified the switch clause adding the following case in line 171
	case "js":
		$content_type ="application/javascript";
		break;

With this change, Kaltura server sends custom javascript uploaded via Kaltura API with content-type 'application/javascript', Chrome 42 executes it, and the player works fine.
I have tested it with a kaltura all-in-one server installed on a virtual machine at my office.

Please, let me know if this change is enough or if more things have to be taken into account in order to pass more exhaustive tests.

**Comment by DBezemer** [comment]
Please open a pull request for this @rafamayoralas

**Comment by jessp01** [comment]
Closing this one since pull was merged.
Thanks,
