### ISSUE TITLE
Apache ssl issue reoccuring

### ISSUE THREAD

**Issue by afrogeex** [kaltura/server#2584]
Hello Jess,

Here's an issue that's recurring in my SSL single instance install.

/etc/init.d/httpd restart

Stopping httpd:                                            [  OK  ]
Starting httpd: httpd: Syntax error on line 221 of /etc/httpd/conf/httpd.conf: Syntax error on line 5 of /etc/httpd/conf.d/zzzkaltura.conf: Include directory '/etc/httpd/@APP_DIR@/configurations/apache/conf.d' not found
                                                           [FAILED]

I tried the fix suggested here: https://github.com/kaltura/server/pull/2384/files to no avail. Do help if you may.

Rgds.

**Comment by acheckley** [comment]
Hi Afrogeex,

The SSL issue in your message relates to something slightly different. A port token was added onto a full port path already contaiing a port. I've had to work on another project recently but will be looking at the SSL installer in a couple of days so will be happy to join in the conversation.

I remember that there were a few bugs with the SSL installer and I intend to explore them very soon.

Andrew

**Comment by acheckley** [comment]
Hi Afrogeex,

I've attached the solution in my bug reports here:

https://github.com/kaltura/platform-install-packages/issues/406

Use an editor like vi/vim/nano to open your con file.

nano /etc/httpd/conf.d/zzzkaltura.conf

See if you have tokens like @LOG_DIR@

If so - as a work around - 

nano /opt/kaltura/app/configurations/apache/kaltura.conf.template

and manually enter in the paths e.g. /opt/kaltura/logs

Save

Run the installer and your apache problem will be solved.

You will then find a certificate problem with ssl.conf in nano /etc/httpd/conf.d/ssl.conf

Self signed certificates will have been generated by the installer.

Comment out the certificate paths and put your own path in.

It will work.

**Comment by acheckley** [comment]
If you get stuck and want an example of the template file - let me know.

**Comment by jessp01** [comment]
Should all work with the latest version.
Please let me know should you have issues.
