### ISSUE TITLE
reconfigure on ubuntu

### ISSUE THREAD

**Issue by shaharmor** [kaltura/server#2672]
Hi,

Trying to run /opt/kaltura/bin/kaltura-base-config.sh gives:

Exiting as kaltura-base is not installed.
This MAY be because the installation of it was skipped do to SELinux being in 'Enforcing' mode.
Please review: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#disable-selinux---required-currently-kaltura-cant-run-properly-with-selinux
And re-run:
# yum install kaltura-server

**Comment by jessp01** [comment]
And do you have SELinux enabled? you need to check why yum install kaltura-base failed.

**Comment by jessp01** [comment]
Also, if you are using Ubuntu, why are you trying to install RPMs?

**Comment by shaharmor** [comment]
I'm not trying to install RPMs.

I want to reconfigure the kaltura server (Change ports and stuff), as i can't get it to work no matter what i'm trying.

**Comment by jessp01** [comment]
Use 
\# dpkg-reconfigure kaltura-base
\# dpkg-reconfigure kaltura-front
\# dpkg-reconfigure kaltura-batch
