### ISSUE TITLE
Moodle api_v3 access control

### ISSUE THREAD

**Issue by acheckley** [kaltura/server#3014]
Hi Everyone,

I have two bugs with Kaltura CE 10.14 and Moodle plugin v3 (the none-paid-for version using the api_v3, not the KAF) on Moodle 2.6.

I've upgraded from Kaltura CE 5 and suspect that the meta data schema for Moodle has changed subtly since CE 5 because under the Publisher console, the courses do not enter into the correct course ID.

More importantly, only a user can access their own video. It cannot be viewed by anyone else in the course. Again, I suspect this maybe metadata related. All other functionality, including webcam recording is working fine.

From my understanding (though this maybe incorrect), I appreciate that Moodle support is now for the paid-for version using the KAF but it would be really good to keep the open source community route for Moodle going. I'm quite happy using the api_v3. If anyone has any pointers on the changes (or even if I'm in the right area) it would be much appreciated.

Thanks,

Andrew

**Comment by KalturaCommunity** [comment]
Hi Andrew,

Just to be clear, by CE 14, you mean 10.14? when you upgraded from CE 5, 
did you follow:
https://github.com/kaltura/platform-install-packages/tree/Jupiter-10.17.0/doc/kaltura-updater

Thanks,

May the source be with you,

Jess Portnoy

**Comment by kaltura-hooks** [comment]
Hi @acheckley,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by acheckley** [comment]
Hi kaltura-hooks, thanks for the info. I'll take a look at this when I return to work tomorrow.

Also, thank you Jess for the info.

I completed a fresh installation of Kaltura CE 10.14 about 2 months ago.

The Moodle v3 plugin has been working brilliantly with CE5 and Moodle 2.6 for quite sometime now. Using a live Moodle environment clone, I removed the v3 plugins and all associated databases, from Moodle, reinstalled and I switched the CE5 server path to the CE 10.14 server.

Everything looked great.

I uploaded a video on the course, can play it back and view it on different devices. However, my colleague (a fellow teacher) on the course cannot. I've tested uploading a video assignment by logging in as a student role and then by logging in and viewing as a teacher. Again, the student can see their work but as a teacher, I cannot.

All of the videos are in Kaltura Publisher and working fine except that the category filter is not placing them in the course. I can get them into the correct course via the tag system.

I also presume that it maybe just the metadata. I've not explored Kaltura in too much depth but under a video 'Custom Data' section, Moodle Repository Profile, I can see properties for system and course. I'm not sure if these properties are passed correctly in CE 10.14. They are blank in the CE5 version but if I recall correctly, they have enteries in the CE5 database.

Thanks,

Andrew

**Comment by jessp01** [comment]
Hi Andrew,

Thanks, now I understand. So we are not talking about an upgrade from an 
old CE 5 to 10.14 but rather, a clean install of CE 10.14? if so, the 
upgrade link is irrelevant.

Indeed as you said, offical support for Moodle is now done with KAF which 
is not free.

However, I would suggest you start by looking at the error logs on the 
Kaltura server end by using the kaltlog alias. Just type 'kaltlog' and 
make the moodle request and lets see if any obvious errors come up.


May the source be with you,

Jess Portnoy

**Comment by acheckley** [comment]
Thanks Jess. Yes, I thought I was correct in thinking that the paid-for KAF is only supported for Moodle and I appreciate the info. I thought I'd post anyway because the plugin uses the api_v3 which is still supported in Kaltura CE (even if only by other systems) so maybe other plugins have needed subtle updates too. I'll follow you advice with the kaltlog but also track though the changes to see if I can find the root cause. After all, Kaltura is a fantastic media server so it's worth the effort.

**Comment by KalturaCommunity** [comment]
Many thanks, Andrew:)
I will see what I can do from my end as well. Let me know what you see in 
the log..

May the source be with you,

Jess Portnoy

**Comment by acheckley** [comment]
Hi Jess,

I've had a successful morning testing Moodle 2.6 with Kaltura CE 10.14 and have found the bug. In the Publisher account for Moodle, I need to manually assign the video to the course ID under categories and everything works perfectly. I tested this using multiple scenarios.

I'm not too sure on how Kaltura operates in relation to the meta data (whether I can make it assign the course id to the category through this route) or whether it is an update SQL script I need to change but this looks fixable. I'll start having a look shortly. If you have any ideas on the meta data or table, it would be much appreciated.

Thanks,

Andrew

**Comment by jessp01** [comment]
Hi Andrew,

Not sure I understand the exact issue but I can certainly explain how we 
handle metadata:)

I assume you are referring to custom metadata, right? not the basic 
metadata for each entry like name, description, etc?
for custom metadata, you create a metadata profile for the specific 
partner which contains a schema describing it.
You can see an example script here:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.17.0/RPM/scripts/postinst/create_metadata.php

You can also create the schema from GUI in KMC, under Settings->Custom 
data.

Categories are also created per partner. You can create/view these under 
the content->categories tab in KMC. And of course, entries can be attached 
to multiple categories.

If you have a specific question on that, can you please post at 
forum.kaltura.org? I'd like to use github issues for bug reports only.

Thanks,

May the source be with you,

Jess Portnoy

**Comment by acheckley** [comment]
Thanks for the info Jess.

The categories are created automatically (this part is working).

In CE 5, the videos were assigned this category automatically. In CE 10.14, they have to be manually assigned. The automatic assigning is broken. 

To fix Moodle, I need to automate the process of adding the video to the category again.

**Comment by KalturaCommunity** [comment]
Andrew, is it possible you have 'Default Entitlement Enforcement' or 
'End-User Entitlements' checked under 'configure' for your partner in 
Admin Console? that might be the cause if so.. go to the 'Publushers' tab, 
then under your partner, select 'Configure' from the 'Actions' selectbox 
and check.

May the source be with you,

Jess Portnoy

**Comment by acheckley** [comment]
Ah, thanks Jess. I had this enabled. I've unchecked and will now test.

**Comment by KalturaCommunity** [comment]
I believe that will solve it. Please let me know.

May the source be with you,

Jess Portnoy

**Comment by acheckley** [comment]
Hi Jess,

Thanks ever so much. As always, I'm incredibly impressed by your knowledge and appreciative of your help. This is now solved.

**Comment by jessp01** [comment]
Happy to help. I will ask the relevant dev to update the documentation 
accordingly.


May the source be with you,

Jess Portnoy

**Comment by acheckley** [comment]
Hi Jess, I forgot to add that this fixes the access control problem. The videos are still not going into the correct category but I can live without that feature and will look at a solution later on.

**Comment by jessp01** [comment]
Hi Andrew,

Did you ensure the category ID you setup on the Moodle end exists for this 
partner?


May the source be with you,

Jess Portnoy

**Comment by gonenradai** [comment]
as far as I remember, videos are going into categories in Moodle v3 only when you have the repository plugin enabled.
could it be that the kaltura repository plugin is disabled?

**Comment by acheckley** [comment]
Hi Jess and gonenradai

I can confirm that the category ID setup on Moodle exists for this partner and I've checked that the plugin is not disabled. 

Therefore, these factors aren't causing the problem. I'll have a look at this in the near future and be happy to detail my findings.

Thanks,

Andrew

**Comment by KalturaCommunity** [comment]
Thanks, Andrew. I would suggest checking the logs for errors. Whatever the 
issue is, it should be reflected in the logs.
As I mentioned before, you can use the 'kaltlog' alias for locating errors 
and then open the relevant log and look around the error string. You 
should also be able to track the relevant API calls made, look for the one 
that was suppose to attach the entry to the relevant category.

May the source be with you,

Jess Portnoy
