### ISSUE TITLE
Kaltura KRecord.swf not working fine

### ISSUE THREAD

**Issue by omerpucit** [kaltura/server#3303]
I am going to attach screen shots of audio/video recoding issue, when i open KRecord.swf from my site url i mean to say like http://mysiteurl/media_record/KRecord.swf its working fine but on my site in default canvas popup its not working fine

First  one image is for when i click on record its start recording
![screen shot 2015-10-12 at 5 00 20 pm](https://cloud.githubusercontent.com/assets/743199/10427453/510f3e38-7103-11e5-9ba7-10eab067315e.png)

But when i click on stop recording its stuck it always show like connecting....
the image is here

![screen shot 2015-10-12 at 5 00 03 pm](https://cloud.githubusercontent.com/assets/743199/10427409/ec51f328-7102-11e5-8ed7-7a8dc51eac64.png)

Please let me know what is the exact issue.

Thanks.

**Comment by kaltura-hooks** [comment]
Hi @omerpucit,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by omerpucit** [comment]
Thanks for your quick reply of this issue.

Let me send you detail error.

Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted? If self hosted, are you using the RPM or deb install?

I am using the self-hosted Kaltura deployment. And i have installed it on RPM using this link
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md
And i am using mariadb mysql service.

Packages installed. When using RPM, paste the output for:
    # rpm -qa "kaltura*"
......output for above command starting from here......
[root@video ~]# rpm -qa "kaltura*"
kaltura-segmenter-1.0-1.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-release-10.19.0-1.noarch
kaltura-html5-studio-v2.0.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-base-10.19.0-10.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-monit-5.6-15.x86_64
kaltura-nginx-1.8.0-8.x86_64
kaltura-html5lib-v2.34-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-server-10.19.0-1.noarch
kaltura-libfaac-1.28-1.x86_64
kaltura-sphinx-2.2.1-17.x86_64
kaltura-ffmpeg-2.7.2-1.x86_64
kaltura-front-10.19.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-dwh-9.5.0-1.noarch
kaltura-batch-10.19.0-1.noarch
kaltura-red5-1.0.3-3.x86_64
kaltura-postinst-1.0.28-17.noarch
kaltura-libopencore-amr-0.1.3-1.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-kmc-v5.39.8-2.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-ffmpeg-aux-0.6-2.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-sshpass-1.05-1.x86_64
......output for command rpm -qa "kaltura*" ending here......

If running a self hosted ENV - provide the MySQL server version used
mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux (x86_64) using readline 5.1

If running a self hosted ENV - is this a single all in 1 server or a cluster?
I am using cloud server

If running a self hosted ENV, while making the problematic request, run:
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"

..... out put for above command starting from here......

tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Mon Oct 12 19:34:21.146618 2015] [:error] [pid 18596] [client 182.180.114.46:54841] PHP Notice:  Array to string conversion in /opt/kaltura/app/plugins/event_notification/lib/model/data/kEventObjectChangedCondition.php on line 70, referer: http://edulms.com.cn/courses/2/discussion_topics/2
[Mon Oct 12 19:37:52.909856 2015] [:error] [pid 32677] [client 113.207.76.72:20055] script '/opt/kaltura/app/alpha/web/wp-cron.php' not found or unable to stat
--
[2015-10-10 01:46:36]exception 'Exception' with message 'Configuration file [/opt/kaltura/app/configurations/sphinx/populate/iZ94gfio8auZ.ini] not found.' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/sphinx_search/scripts/populateFromLog.php(36): KalturaLog::err('Configuration f...')
--
[2015-10-12 04:52:34]exception 'Exception' with message 'Configuration file [/opt/kaltura/app/configurations/sphinx/populate/iZ94gfio8auZ.ini] not found.' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/sphinx_search/scripts/populateFromLog.php(36): KalturaLog::err('Configuration f...')
--
==> /opt/kaltura/log/batch/bulkupload-0-2015-10-12.err.log <==
PHP Notice:  Undefined offset: 12 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 13 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 14 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 12 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 13 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 14 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 12 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 13 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 14 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240

--
==> /opt/kaltura/log/batch/import-0-2015-10-12.err.log <==
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220

--
==> /opt/kaltura/log/batch/import-1-2015-10-12.err.log <==
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220

..... out put for above command ending from here......

Extra info i am running Red5 streaming server using these commands

# yum install kaltura-red5
Request http://hostname:5080
Click 'Install a ready-made application'
Mark 'OFLA Demo' and click 'Install'
Edit /usr/lib/red5/webapps/oflaDemo/index.html and replace 'localhost' with your actual Red5 hostname or IP
Test OflaDemo by making a request to http://hostname:5080/oflaDemo/ and playing the sample videos
Run:

And its working fine. 

Now about the issue, i am using canvas latest on my another cloud machine.

My streaming server is running here
http://video.edulms.com.cn:5080/
Also Kaltura is running on same server.

And Canvas is running here
http://edulms.com.cn

I can give you credentials as well if needed. Now let me tell you more about the issue.

When i just go for new announcement and in that page when i just click on recording video. Its start my recording using my webcam working fine. But when i stop the recording it should play recorded video but its never return back its always show 'Connecting'

The below image 1 is when i saw recording button and the 2 is when i just click on stop recording. So as per my understanding the issue is with kaltura side or may be with katura red5 streaming server.

1. https://cloud.githubusercontent.com/assets/743199/10427453/510f3e38-7103-11e5-9ba7-10eab067315e.png

2. https://cloud.githubusercontent.com/assets/743199/10427409/ec51f328-7102-11e5-8ed7-7a8dc51eac64.png


Thanks and let me know if you want further information.

Thanks.

**Comment by omerpucit** [comment]
Also please ignore this one exception, it was relate to server hostname which was wrong, i just corrected my hostname.

[2015-10-12 04:52:34]exception 'Exception' with message 'Configuration file [/opt/kaltura/app/configurations/sphinx/populate/iZ94gfio8auZ.ini] not found.' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/sphinx_search/scripts/populateFromLog.php(36): KalturaLog::err('Configuration f...')

**Comment by jessp01** [comment]
Hello,

To better understand the problem: does it only happen when using the web recording from Canvas? does it work well when using it from KMC?

**Comment by omerpucit** [comment]
Hi,

Yes its working fine in Kaltura side but its not working in Canvas side, some time it works but like 1 out of 100. So configuration is okay but there is something wrong with kaltura-streaming or may be with player. As i mentioned i have downloaded a kaltura side player which works fine but right after recording when i click on save it don't have the same api like kaltura want 
i think which is 'addentry' something.

The working player is on this url http://edulms.com.cn/media_record/KRecord.swf.working
and this is the original player which came from canvas http://edulms.com.cn/media_record/KRecord.swf which have the right api for saving the media into text editor.

I hope it can help you.

Thanks.

**Comment by atarsh** [comment]
Referring directly to the swf is not expected to work. krecord requires a bunch of other parameters (flashvars), most importantly a KS.
see here:
http://knowledge.kaltura.com/krecord-website-integration-guide

PS - KMC doesn't use kRecord, it uses KCW. if KCW is working in your KMC you can assume your media server is configured correctly, but that's all it means.

**Comment by omerpucit** [comment]
Hi Atarsh,

Thanks for it but the main thing is it is working  fine to KMC but in canvas its not working fine.

**Comment by atarsh** [comment]
can you share a link + creds to your canvas installation? as explained before, the swf alone is not helping. your issue will be around the integration.

**Comment by omerpucit** [comment]
Hi Thanks for your interest you can go here and test it.

url: http://edulms.com.cn/courses/2/announcements

user:  test
password: testing123

I have just created it for the testing purpose and using above url you can
add a new announcement and in that section you can play with recording
section.

Thanks.

On Tue, Oct 13, 2015 at 1:27 PM, atarsh <notifications@github.com> wrote:

> can you share a link + creds to your canvas installation? as explained
> before, the swf alone is not helping. your issue will be around the
> integration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaltura/server/issues/3303#issuecomment-147646259>.
>



-- 

-- 
Regards,

Umer Bilal
Senior Software Engineer


UnlockTech
Contact: (+92) 313 4487430, 321 9898229
Skype: omer.afzaal
Email: omerpucit@gmail.com, sams.solutionz@gmail.com <omerpucit@gmail.com>

**Comment by atarsh** [comment]
as soon as I disabled the autopreview I managed to save the entry (you can see the one with the flower), this means for some reason when krecord tries to play the recorded file it fails to get it.
you have to make sure your media server is configured properly, and the folder where it saves the recorded content is accessible.
I see you made modifications to the flash file (the audio bars for example), if you changed stuff in the way it does the playback I will not be able to help you.

**Comment by omerpucit** [comment]
This time i have connected Wowza streaming cloud with kaltura, like i just created a rtmp streamer and just updated from canvas admin side updated "RTMP Domain" but it still showing same behaviour like my own red5 server.

Can you please check it.

Thanks.

**Comment by omerpucit** [comment]
I would like to share more information about it

I have created a Streamer using Wowza Streaming cloud like in this way

Have a look on attached images

![screen shot 2015-10-14 at 1 46 58 am](https://cloud.githubusercontent.com/assets/743199/10467882/9ba0873c-7215-11e5-84a7-d5a272b9b000.png)
![screen shot 2015-10-14 at 1 46 51 am](https://cloud.githubusercontent.com/assets/743199/10467883/9ba44840-7215-11e5-9445-1b9ad835e7c6.png)


In textual the detail is

Source Aspect Ratio 
16:9 (Widescreen) -- 384 x 216

Source Connection Information

Primary Server	rtmp://cf7264.entrypoint.cloud.wowza.com/app-f293 (54.64.135.216)
Host Port	1935
Stream Name	b786e765

My Kaltura plugin side settings as attached images

![screen shot 2015-10-14 at 1 49 01 am](https://cloud.githubusercontent.com/assets/743199/10468051/5d7b1ea8-7216-11e5-8fb4-0035c690aa41.png)
![screen shot 2015-10-14 at 1 48 56 am](https://cloud.githubusercontent.com/assets/743199/10468052/5d809630-7216-11e5-8b9f-b5adca03499d.png)

detail in textual

RTMP Domain: cf7264.entrypoint.cloud.wowza.com/app-f293

I hope it should fix now.


## Also can you please send me some working streaming url so that i can test with them whether this player is working fine or not.

Thanks.

**Comment by atarsh** [comment]
I'm sorry, I don't have a url that streams video constantly, also I'm not sure I understand what you mean - krecord is not a player. it's a recorder. the only thing you can play with it is the stream you just recorded.

**Comment by omerpucit** [comment]
Hi,

Actually i am using red5 server for webcam recording i can see one thing may be that is the issue


When i just opened recording then it is creating files in such way

i have red5 streams recording here
/usr/lib/red5/webapps/oflaDemo/streams

and when i run the command ls -lh it is showing it as
-rw-r--r--. 1 root   root    146K Oct 14 15:38 A94DA1C9-2163-9428-D9E9-6548FA56931B.flv
-rwxrwxr-x. 1 apache kaltura  28K Oct 13 19:50 oflaDemo.flv
-rwxrwxr-x. 1 apache kaltura  21K Oct 13 19:51 test123.flv

As you can see i have try to change the user group as well as the chmod but the thing is when ever i record red5 creating streaming using user root and it is not working in right privileges so it may be a issue??

Can you please help me how i can change the permissions for newly created streams. I have tried to run these commands.
chown apache:kaltura /usr/lib/red5/webapps/oflaDemo/streams -R
chmod 755 /usr/lib/red5/webapps/oflaDemo/streams -R

But when recording is creating in this directory its again have privileges like aboe.

Thanks.

**Comment by KalturaCommunity** [comment]
Hi Umer,

owner apache and group kaltura is fine. The web I/F runs as apache, having 
it as owner is all you need, kaltura group is needed cause batch runs as 
the 'kaltura' user. This is not the issue.

Red5 - we are transmitting f4v with krecord, Red5 started supporting these 
at a certain stage but I am not sure how good the support is, I am 
currently evaluating this and will let you know.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by omerpucit** [comment]
Hi,

Can you please tell me one thing is Wowza will work with Canvas side too if i buy. I know about how to configure it with kaltura side but the thing is like oflademo which type of wowza streaming engine or streaming cloud i should use which should also work to Canvas Video/Audio recording using KRecrod.swf

Thanks.

**Comment by jessp01** [comment]
We are currently testing integration with Wowza 4. I will let you know as 
to the results. Your inquery caught us just as we started looking into 
it:)
I can tell you that at the moment, in our SaaS ENV, we use Adobe FMS but 
our plan is to recommend Wowza for webcam recording and live streaming 
purposes.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by omerpucit** [comment]
Hi Again,

I run red5 in debug mode and i can see this error every time when i am recording video but its working fine with audio recording.

Here is the response of Red5 Server

[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.StreamService - closeStream: streamId=1, connection=RTMPMinaConnection from 182.180.114.46 (in: 41742 out: 3979) session: CKAIJ7OQWEFN6 state: connected
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.StreamService - Stream not found: streamId=1, connection=RTMPMinaConnection from 182.180.114.46 (in: 41742 out: 3979) session: CKAIJ7OQWEFN6 state: connected
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.ClientBroadcastStream - Stream start: EDA70E91-F2AC-E34E-7214-65F52496D10C
[DEBUG] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.RecordingListener - Recording file: /usr/lib/red5/webapps/oflaDemo/streams/EDA70E91-F2AC-E34E-7214-65F52496D10C.flv
[DEBUG] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.RecordingListener - Context contains a file consumer
[DEBUG] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.RecordingListener - File name: EDA70E91-F2AC-E34E-7214-65F52496D10C.flv
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.demos.oflaDemo.Application - W3C x-category:stream x-event:record-start c-ip:182.180.114.46 x-sname:e8e6ce2b-ec76-461f-a50e-81efdfeacdc2 x-file-name:EDA70E91-F2AC-E34E-7214-65F52496D10C.flv
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.StreamService - closeStream: streamId=2, connection=RTMPMinaConnection from 182.180.114.46 (in: 81579 out: 4306) session: CKAIJ7OQWEFN6 state: connected
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.demos.oflaDemo.Application - W3C x-category:stream x-event:record-stop c-ip:182.180.114.46 x-sname:e8e6ce2b-ec76-461f-a50e-81efdfeacdc2 x-file-name:EDA70E91-F2AC-E34E-7214-65F52496D10C.flv
[DEBUG] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.RecordingListener - Event queue was not empty on stop, processing...
[DEBUG] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.RecordingListener - Stream data size was 0, sending empty audio message
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.demos.oflaDemo.Application - W3C x-category:stream x-event:unpublish c-ip:182.180.114.46 cs-bytes:81579 sc-bytes:4454 x-sname:e8e6ce2b-ec76-461f-a50e-81efdfeacdc2 x-file-length:6 x-name:EDA70E91-F2AC-E34E-7214-65F52496D10C
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.demos.oflaDemo.Application - W3C x-category:stream x-event:recordstop c-ip:182.180.114.46 cs-bytes:81579 sc-bytes:4608 x-sname:e8e6ce2b-ec76-461f-a50e-81efdfeacdc2 x-file-name:EDA70E91-F2AC-E34E-7214-65F52496D10C.flv x-file-length:6 x-file-size:81579
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.StreamService - closeStream: streamId=2, connection=RTMPMinaConnection from 182.180.114.46 (in: 81608 out: 4608) session: CKAIJ7OQWEFN6 state: connected
[INFO] [RTMPExecutor#CKAIJ7OQWEFN6-1] org.red5.server.stream.StreamService - Stream not found: streamId=2, connection=RTMPMinaConnection from 182.180.114.46 (in: 81608 out: 4608) session: CKAIJ7OQWEFN6 state: connected


## The video recording is working fine on other site

The url of external site is
http://www.technogumbo.com/tutorials/Recording-Decent-Quality-Video-And-Audio-With-Flash-and-Red5/
Just scroll down and you will see rtmp server url and once you will click on start recording its working fine as well as its playing the video as well.

But in Canvas video recording its not working fine.

Thanks.

**Comment by omerpucit** [comment]
Hi,

You can test that using

**Comment by omerpucit** [comment]
You can fix this issue using this site code

http://www.technogumbo.com/tutorials/Recording-Decent-Quality-Video-And-Audio-With-Flash-and-Red5/

**Comment by omerpucit** [comment]
Another helping material
http://www.technogumbo.com/tutorials/Recording-Combined-Audio-and-Video-Streams-With-Flash-and-Red5-1-0-2-SNAPSHOT-or-FMS/

**Comment by jessp01** [comment]
Closing as krecord has been declared obsolete and is no longer supported.
