### ISSUE TITLE
Unable to migrate kaltura from AWS to Physical Centos Linux server

### ISSUE THREAD

**Issue by panigh** [kaltura/server#3315]
We did the following steps for Kaltura migration.
1. Installed LAMP and kaltura in the "target" physical server
2. Make sure it is showing KAC and KMC screens
3. Backup the "kaltura" database of "source" production Kaltura database
4. rsync -r "source host:/opt/kaltura/web" "target host:/opt/kaltura/web"
5. Restore database dump of "Source" kaltura database to "target" host.
6. Make sure the partner_id=-1 in partner table of target db not changed due to this restoration .
7. After this when tried to open KAC gives "Invalid_KS" error
8. while trying to run the following I'm getting error
php /opt/kaltura/app/deployment/updates/update.php

[root@konnectdev kaltura_db_dump]# php /opt/kaltura/app/deployment/updates/update.php
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/ssh2.so' - /usr/lib64/php/modules/ssh2.so: cannot open shared object file: No such file or directory in Unknown on line 0
classname=>KalturaPDO
phptype=>mysql
database=>kaltura
hostspec=>localhost
user=>kaltura
password=>kaltura
dsn=>mysql:host=localhost;port=3306;dbname=kaltura;
options=>Array
port=>3306
host=>localhost
dbname=>kaltura
PHP Warning:  mysql_free_result() expects parameter 1 to be resource, boolean given in /opt/kaltura/app/deployment/updates/update.php on line 195
PHP Notice:  Undefined variable: version in /opt/kaltura/app/deployment/updates/update.php on line 197
PHP Warning:  mysql_free_result() expects parameter 1 to be resource, boolean given in /opt/kaltura/app/deployment/updates/update.php on line 216
PHP Notice:  Undefined variable: res in /opt/kaltura/app/deployment/updates/update.php on line 218
Executing [mysql -hlocalhost -ukaltura -pkaltura -P3306 kaltura < /opt/kaltura/app/deployment/updates/create_version_mng_table.sql]
ERROR 1142 (42000) at line 1: CREATE command denied to user 'kaltura'@'localhost' for table 'version_management'
Failed to run [mysql -hlocalhost -ukaltura -pkaltura -P3306 kaltura < /opt/kaltura/app/deployment/updates/create_version_mng_table.sql]

Executing [mysql -hlocalhost -ukaltura -pkaltura -P3306 kaltura < /opt/kaltura/app/deployment/updates/sql/2013_04_15_suspend_jobs_table.sql]
ERROR 1142 (42000) at line 1: CREATE command denied to user 'kaltura'@'localhost' for table 'batch_job_lock_suspend'
Failed to run [mysql -hlocalhost -ukaltura -pkaltura -P3306 kaltura < /opt/kaltura/app/deployment/updates/sql/2013_04_15_suspend_jobs_table.sql]

IS THE ABOVE IS THE CORRECT WAY OF DOING MIGRATION???

ARE THERE ANY OFFICIAL DOC HOW TO MIGRATE KALTURA environment from AWS to physical server???

Appreciate if some one could throw some light.

Currently
I saw some document from the internet as below for doing the kaltura server migration.
I used the following
Export your CE 5 Data Base
Run the following command (replace [user] and [password] with relevant values:
1
mysqldump kaltura -u[user] -p[password] > kaltura.sql
Install CE 5.0
Backup CE5 installation data, /opt/kaltura/web directory and install Kaltura CE5.
Rsync back up web directory to your CE5 web directory
For example
1
rsync -r pathtobackup/web/ /opt/kaltura/web/
Replace values for (only) batch partner “-1” from new database with values in backup kaltura.sql file. Replace old values with new one in kaltura.sql
Import your CE5 DataBase from previous installation
Run the following command (replace [user] and [password] with relevant values):
1
mysql kaltura -u[user] -p[password] < kaltura.sql
Run the migration scripts
1
php /opt/kaltura/app/deployment/updates/update.php
If still videos do not display under content tab execute this script
1
php /opt/kaltura/app/scripts/utils/updatePartnerEntries2Sphinx.php “partner_id”
It should execute without errors else execute again.
If videos do not play
We did the following steps for Kaltura migration.

1
chmod -R 777 /opt/kaltura/web/content/entry/data
Execute the script below if you are unable to see newly uploaded content after rebooting server
1
/usr/bin/php /opt/kaltura/app/plugins/sphinx_search/scripts/populateFromLog.php /opt/kaltura/app/plugins/sphinx_search/scripts/configs/server-sphinx.php
Run the Above script as a background process. Follow Instructions below
create a file as sphinx_server.sh and copy the above code into it as
1
2
#!/bin/sh
/usr/bin/php /opt/kaltura/app/plugins/sphinx_search/scripts/populateFromLog.php /opt/kaltura/app/plugins/sphinx_search/scripts/configs/server-sphinx.php > /dev/null 2>&1 &
save and change its permissions to chmod +x sphinx_server.sh
Add the line below in /etc/rc.local so that it starts executing after server is rebooted
- See more at: http://www.oodlestechnologies.com/blogs/Restoring-Kaltura-CE5#sthash.B8rIbv8m.dpuf

**Comment by kaltura-hooks** [comment]
Hi @panigh,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello,

See https://github.com/kaltura/platform-install-packages/tree/Kajam-11.0.0/doc/kaltura-updater/core
This procedure was successfully applied when migrating from Falcon [CE6] to the RPM version of CE 9.
For there onwards, all is done using a relatively simple upgrade procedure which you can find here:
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#upgrade-kaltura

A similar procedure can be done to upgrade to the deb version, in the event you prefer running on Debian/Ubuntu.

**Comment by jessp01** [comment]
For upgrading from CE 5 [Eagle] adding eagle_2011_11_22 to the list of RELEASES before RELEASES="falcon_2012_08_20" here:
https://github.com/kaltura/platform-install-packages/blob/Kajam-11.0.0/doc/kaltura-updater/core/config.sample.sh
should work.
