### ISSUE TITLE
How i can integrate streaming server which is hosted on different server

### ISSUE THREAD

**Issue by omerpucit** [kaltura/server#3328]
Hi,

I have installed adobe media player on different server and my kaltura server is different. I am doing webcam recording from canvas side using kaltura. Now the point is my kaltura server is different and my streaming server is different, how i can integrate it in such way so that videos should be saved to kaltura side once i click on save button to canvas side recording.

May i need to update kaltura api which is index.php/partnerservices2/addentry?entry1%5Fname=admin

Can any one help me.

Thanks.

**Comment by kaltura-hooks** [comment]
Hi @omerpucit,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by omerpucit** [comment]
Thanks for your quick reply of this issue.

Let me send you detail error.

Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted? If self hosted, are you using the RPM or deb install?

I am using the self-hosted Kaltura deployment. And i have installed it on RPM using this link
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md
And i am using mariadb mysql service.

Packages installed. When using RPM, paste the output for:
    # rpm -qa "kaltura*"
......output for above command starting from here......
[root@video ~]# rpm -qa "kaltura*"
kaltura-segmenter-1.0-1.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-release-10.19.0-1.noarch
kaltura-html5-studio-v2.0.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-base-10.19.0-10.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-monit-5.6-15.x86_64
kaltura-nginx-1.8.0-8.x86_64
kaltura-html5lib-v2.34-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-server-10.19.0-1.noarch
kaltura-libfaac-1.28-1.x86_64
kaltura-sphinx-2.2.1-17.x86_64
kaltura-ffmpeg-2.7.2-1.x86_64
kaltura-front-10.19.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-dwh-9.5.0-1.noarch
kaltura-batch-10.19.0-1.noarch
kaltura-red5-1.0.3-3.x86_64
kaltura-postinst-1.0.28-17.noarch
kaltura-libopencore-amr-0.1.3-1.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-kmc-v5.39.8-2.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-ffmpeg-aux-0.6-2.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-sshpass-1.05-1.x86_64
......output for command rpm -qa "kaltura*" ending here......

If running a self hosted ENV - provide the MySQL server version used
mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux (x86_64) using readline 5.1

If running a self hosted ENV - is this a single all in 1 server or a cluster?
I am using cloud server

If running a self hosted ENV, while making the problematic request, run:
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"

..... out put for above command starting from here......

tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Mon Oct 12 19:34:21.146618 2015] [:error] [pid 18596] [client 182.180.114.46:54841] PHP Notice:  Array to string conversion in /opt/kaltura/app/plugins/event_notification/lib/model/data/kEventObjectChangedCondition.php on line 70, referer: http://edulms.com.cn/courses/2/discussion_topics/2
[Mon Oct 12 19:37:52.909856 2015] [:error] [pid 32677] [client 113.207.76.72:20055] script '/opt/kaltura/app/alpha/web/wp-cron.php' not found or unable to stat
--
[2015-10-10 01:46:36]exception 'Exception' with message 'Configuration file [/opt/kaltura/app/configurations/sphinx/populate/iZ94gfio8auZ.ini] not found.' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/sphinx_search/scripts/populateFromLog.php(36): KalturaLog::err('Configuration f...')
--
[2015-10-12 04:52:34]exception 'Exception' with message 'Configuration file [/opt/kaltura/app/configurations/sphinx/populate/iZ94gfio8auZ.ini] not found.' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/sphinx_search/scripts/populateFromLog.php(36): KalturaLog::err('Configuration f...')
--
==> /opt/kaltura/log/batch/bulkupload-0-2015-10-12.err.log <==
PHP Notice:  Undefined offset: 12 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 13 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 14 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 12 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 13 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 14 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 12 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 13 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240
PHP Notice:  Undefined offset: 14 in /opt/kaltura/app/plugins/bulk_upload/csv/batch/BulkUploadEntryEngineCsv.php on line 240

--
==> /opt/kaltura/log/batch/import-0-2015-10-12.err.log <==
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220

--
==> /opt/kaltura/log/batch/import-1-2015-10-12.err.log <==
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220
PHP Notice:  curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /opt/kaltura/app/infra/general/KCurlWrapper.class.php on line 220

..... out put for above command ending from here......

Extra info i am running Red5 streaming server using these commands

# yum install kaltura-red5
Request http://hostname:5080
Click 'Install a ready-made application'
Mark 'OFLA Demo' and click 'Install'
Edit /usr/lib/red5/webapps/oflaDemo/index.html and replace 'localhost' with your actual Red5 hostname or IP
Test OflaDemo by making a request to http://hostname:5080/oflaDemo/ and playing the sample videos
Run:

And its working fine. 

Now about the issue, i am using canvas latest on my another cloud machine.

My streaming server is running here
http://video.edulms.com.cn:5080/
Also Kaltura is running on same server.

And Canvas is running here
http://edulms.com.cn

I can give you credentials as well if needed. Now let me tell you more about the issue.

When i just go for new announcement and in that page when i just click on recording video. Its start my recording using my webcam working fine. But when i stop the recording it should play recorded video but its never return back its always show 'Connecting'

The below image 1 is when i saw recording button and the 2 is when i just click on stop recording. So as per my understanding the issue is with kaltura side or may be with katura red5 streaming server.

1. https://cloud.githubusercontent.com/assets/743199/10427453/510f3e38-7103-11e5-9ba7-10eab067315e.png

2. https://cloud.githubusercontent.com/assets/743199/10427409/ec51f328-7102-11e5-8ed7-7a8dc51eac64.png


Thanks and let me know if you want further information.

Thanks.

**Comment by omerpucit** [comment]
Hi,

I have installed adobe media player on different server and my kaltura server is different. I am doing webcam recording from canvas side using kaltura. Now the point is my kaltura server is different and my streaming server is different, how i can integrate it in such way so that videos should be saved to kaltura side once i click on save button to canvas side recording.

May i need to update kaltura api which is index.php/partnerservices2/addentry?entry1%5Fname=admin

Can any one help me.

Thanks.

**Comment by zoharbabin** [comment]
@omerpucit - did you mean Adobe Media Server?
You should follow the guidelines in the cluster deployment doc for how to configure multiple servers:
https://github.com/kaltura/platform-install-packages/blob/master/doc/rpm-cluster-deployment-instructions.md#the-streaming-server

**Comment by jessp01** [comment]
Closing since no feedback was provided. If you have additional questions, please post to forum.kaltura.org as we'd rather keep the github issue section for bug reports exclusively and the forum for general questions or ENV specific issues.
