### ISSUE TITLE
Kaltura- Internal Database Error, while uploading and deleting the files.

### ISSUE THREAD

**Issue by infra-oodles** [kaltura/server#3697]
I am using kaltura version 11.20 on centos 6.7 machine and mysql 5.1.73 . It was running fine since last one month. Today , I ran out of disk issue and I have deleted kaltura_api_v3.log and kaltura_populate.log log files.

Now after this , I am getting internal database error in uploading and deleting the content.

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Kaltlog  is below
--------
2016-01-11 23:58:59 [0.000121] [1120303733] [11] [BATCH] [KalturaClientBase->doQueue] INFO: execution time for [https://kaltura.babyflix.net/api_v3/service/dropfolder_dropfolder/action/list]: [0.16753101348877]
2016-01-11 23:58:59 [0.000153] [1120303733] [12] [BATCH] [KAsyncDropFolderWatcher->getDropFoldersList] ERR: exception 'Exception' with message 'Cannot get drop folder list - Internal database error' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(108): KalturaLog::err('Cannot get drop...')
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 362
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'couldn't connect to host' in /opt/kaltura/app/batch/client/KalturaClientBase.php:362
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(1131): KalturaClientBase->doQueue()
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 894
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(634): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 894
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(634): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 362
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'couldn't connect to host' in /opt/kaltura/app/batch/client/KalturaClientBase.php:362
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(1116): KalturaClientBase->doQueue()
--
==> /opt/kaltura/log/batch/synchronizedistribution-0-2016-01-12.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaPlugins/KalturaContentDistributionClientPlugin.php(2804): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 894
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal server error occurred' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4124): KalturaClientBase->throwExceptionIfError(Array)
--
2016-01-12 06:21:06 [0.000652] [::1] [75185419] [15] [API] [KalturaStatement->execute] DEBUG: /* kaltura.babyflix.net[75185419][propel] */ INSERT INTO scheduler_status (`ID`,`CREATED_AT`,`UPDATED_AT`,`SCHEDULER_ID`,`SCHEDULER_CONFIGURED_ID`,`TYPE`,`VALUE`) VALUES (NULL,'2016-01-12 06:21:06','2016-01-12 06:21:06','1','99524','7','1')
2016-01-12 06:21:06 [0.000380] [::1] [75185419] [16] [API] [BasePeer::doInsert] ERR: exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'worker_configured_id' doesn't have a default value' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(408): KalturaLog::err('SQLSTATE[HY000]...')
--
2016-01-12 06:21:06 [0.000470] [::1] [75185419] [17] [API] [KalturaFrontController->getExceptionObject] ALERT: exception 'PropelException' with message 'Unable to execute INSERT statement. [wrapped: SQLSTATE[HY000]: General error: 1364 Field 'worker_configured_id' doesn't have a default value]' in /opt/kaltura/app/vendor/propel/util/BasePeer.php:299
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/om/BaseSchedulerStatusPeer.php(766): BasePeer::doInsert(Object(Criteria), Object(KalturaPDO))
--
==> /opt/kaltura/log/batch/kschedulehelper-0-2016-01-12.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(634): KalturaClientBase->throwExceptionIfError(Array)

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Kaltura_api_v3.log

When I am trying to upload a content , I am getting following error in kaltura_api_v3.log

2016-01-12 05:32:21 [0.003574] [::1] [2018493301] [8] [API] [KalturaPDO->__construct] DEBUG: conn took - 0.00036001205444336 seconds to mysql:host=127.0.0.1;port=3306;dbname=kaltura;
2016-01-12 05:32:21 [0.000381] [::1] [2018493301] [9] [API] [Propel::initConnection] NOTICE: total conn took 0.00080704689025879 mysql:host=127.0.0.1;port=3306;dbname=kaltura;
2016-01-12 05:32:21 [0.000133] [::1] [2018493301] [10] [API] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2016-01-12 05:32:21 [0.002660] [::1] [2018493301] [11] [API] [KalturaStatement->execute] DEBUG: /* kaltura.babyflix.net[2018493301][propel3] */ SELECT scheduler.ID, scheduler.CREATED_AT, scheduler.CREATED_BY, scheduler.UPDATED_AT, scheduler.UPDATED_BY, scheduler.CONFIGURED_ID, scheduler.NAME, scheduler.DESCRIPTION, scheduler.STATUSES, scheduler.LAST_STATUS, scheduler.HOST FROM `scheduler` WHERE scheduler.CONFIGURED_ID='99524' LIMIT 1
2016-01-12 05:32:21 [0.000497] [::1] [2018493301] [12] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.00037002563476562 seconds
2016-01-12 05:32:21 [0.005051] [::1] [2018493301] [13] [API] [KalturaPDO->__construct] DEBUG: conn took - 0.00023317337036133 seconds to mysql:host=127.0.0.1;port=3306;dbname=kaltura;
2016-01-12 05:32:21 [0.000145] [::1] [2018493301] [14] [API] [Propel::initConnection] NOTICE: total conn took 0.00043892860412598 mysql:host=127.0.0.1;port=3306;dbname=kaltura;
2016-01-12 05:32:21 [0.000586] [::1] [2018493301] [15] [API] [KalturaStatement->execute] DEBUG: /* kaltura.babyflix.net[2018493301][propel] */ INSERT INTO scheduler_status (`ID`,`CREATED_AT`,`UPDATED_AT`,`SCHEDULER_ID`,`SCHEDULER_CONFIGURED_ID`,`TYPE`,`VALUE`) VALUES (NULL,'2016-01-12 05:32:21','2016-01-12 05:32:21','1','99524','7','1')
2016-01-12 05:32:21 [0.000350] [::1] [2018493301] [16] [API] [BasePeer::doInsert] ERR: exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'worker_configured_id' doesn't have a default value' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(408): KalturaLog::err('SQLSTATE[HY000]...')

XXXXXXXXXXXXXXXXXXXXXXXXxxx

I have gone through the table scheduler_config and it has values of worker_configured_id for all the records when the kaltura was working properly

**Comment by kaltura-hooks** [comment]
Hi @infra-oodles,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by infra-oodles** [comment]
Hi Kaltura-hooks

Thank you for replying

Earlier it was all working fine, but now the above issue is consistent, and across platforms.
I am unable to upload or delete any data 

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

i'm using self-hosted kaltura deployment and rpm install.

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# rpm -qa "kaltura*"

kaltura-release-11.2.0-1.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-html5lib-v2.37.1-2.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-batch-11.2.0-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-libass-0.9.11-2.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-postinst-1.0.30-2.noarch
kaltura-base-11.2.0-12.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kupload-1.0.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-html5-studio-v2.0.1-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-librtmp-2.3-2.x86_64
kaltura-front-11.2.0-1.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-server-11.2.0-1.noarch
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-monit-5.13-1.x86_64
kaltura-kdp-v2.7.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kmc-v5.39.11-3.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-nginx-1.8.0-9.x86_64
kaltura-dwh-9.5.0-2.noarch


XXXXXXXXXXXXXXXXXXXXXXXXXXX

mysql version -   mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

it is single all in one server

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]" 

==> /opt/kaltura/log/kaltura_apache_errors_ssl.log <==
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/0_s8d16nghvxTmHR,/opt/kaltura/app/cache//html5/v2.37.1/iframe/0_/0_s8d16ngh): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/09WwYQ1,/opt/kaltura/app/cache//html5/v2.37.1/iframe/0/0): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/uiconf-21125-_101-23448195hiOUOc,/opt/kaltura/app/cache//html5/v2.37.1/iframe/23/uiconf-21125-_101-23448195): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/uiconf-21125-_101-23448195mw8Iyo,/opt/kaltura/app/cache//html5/v2.37.1/iframe/23/uiconf-21125-_101-23448195): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/uiconf-21125-_101-234481953nRU2A,/opt/kaltura/app/cache//html5/v2.37.1/iframe/23/uiconf-21125-_101-23448195): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/uiconf-21125-_101-23448195yTgUfO,/opt/kaltura/app/cache//html5/v2.37.1/iframe/23/uiconf-21125-_101-23448195): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/0_s8d16nghCAIVT2,/opt/kaltura/app/cache//html5/v2.37.1/iframe/0_/0_s8d16ngh): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/0vwH4xh,/opt/kaltura/app/cache//html5/v2.37.1/iframe/0/0): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/
[Tue Jan 12 15:46:30 2016] [error] [client 199.30.25.144] PHP Warning:  rename(/tmp/uiconf-21125-_101-23448195bxJRpA,/opt/kaltura/app/cache//html5/v2.37.1/iframe/23/uiconf-21125-_101-23448195): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: https://kaltura.babyflix.net/html5/html5lib/v2.37.1/mwEmbedFrame.php/p/101/uiconf_id/23448195/entry_id/0_s8d16ngh?wid=_101&iframeembed=true&playerId=kaltura_player_1450852146&entry_id=0_s8d16ngh
[Tue Jan 12 16:54:40 2016] [error] [client 157.55.39.111] File does not exist: /opt/kaltura/app/alpha/web/p

--
2015-11-27 11:38:05 [859140684] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:65
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
==> /opt/kaltura/log/batch/convert-0-2016-01-11.err.log <==
PHP Warning:  file_get_contents(/opt/kaltura/tmp/convert/convert_0_qpyffs4o_b5c07.log): failed to open stream: No such file or directory in /opt/kaltura/app/batch/batches/Convert/Engines/KConversionEngine.class.php on line 102
PHP Warning:  file_get_contents(/opt/kaltura/tmp/convert/convert_0_qpyffs4o_e53ff.log): failed to open stream: No such file or directory in /opt/kaltura/app/batch/batches/Convert/Engines/KConversionEngine.class.php on line 102
PHP Warning:  file_get_contents(/opt/kaltura/tmp/convert/convert_0_qpyffs4o_39942.log): failed to open stream: No such file or directory in /opt/kaltura/app/batch/batches/Convert/Engines/KConversionEngine.class.php on line 102
PHP Warning:  file_get_contents(/opt/kaltura/tmp/convert/convert_0_qpyffs4o_aef31.log): failed to open stream: No such file or directory in /opt/kaltura/app/batch/batches/Convert/Engines/KConversionEngine.class.php on line 102
PHP Warning:  file_get_contents(/opt/kaltura/tmp/convert/convert_0_qpyffs4o_ad28b.log): failed to open stream: No such file or directory in /opt/kaltura/app/batch/batches/Convert/Engines/KConversionEngine.class.php on line 102

--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 362
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'couldn't connect to host' in /opt/kaltura/app/batch/client/KalturaClientBase.php:362
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(1293): KalturaClientBase->doQueue()
--
find: `/opt/kaltura/tmp/*/*': No such file or directory
PHP Warning:  file_put_contents(): Only 0 of 5 bytes written, possibly out of free disk space in /opt/kaltura/app/batch/scheduler/KScheduleHelperManager.class.php on line 199
PHP Warning:  file_put_contents(): Only 0 of 5 bytes written, possibly out of free disk space in /opt/kaltura/app/batch/scheduler/KScheduleHelperManager.class.php on line 199
PHP Warning:  file_put_contents(): Only 0 of 4 bytes written, possibly out of free disk space in /opt/kaltura/app/batch/scheduler/KScheduleHelperManager.class.php on line 199

--
find: `/opt/kaltura/web/tmp/*/*': No such file or directory
PHP Warning:  file_put_contents(): Only 0 of 5 bytes written, possibly out of free disk space in /opt/kaltura/app/batch/scheduler/KScheduleHelperManager.class.php on line 199
PHP Warning:  file_put_contents(): Only 0 of 4 bytes written, possibly out of free disk space in /opt/kaltura/app/batch/scheduler/KScheduleHelperManager.class.php on line 199

--
2016-01-11 23:58:59 [0.000121] [1120303733] [11] [BATCH] [KalturaClientBase->doQueue] INFO: execution time for [https://kaltura.babyflix.net/api_v3/service/dropfolder_dropfolder/action/list]: [0.16753101348877]
2016-01-11 23:58:59 [0.000153] [1120303733] [12] [BATCH] [KAsyncDropFolderWatcher->getDropFoldersList] ERR: exception 'Exception' with message 'Cannot get drop folder list - Internal database error' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(108): KalturaLog::err('Cannot get drop...')
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 362
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'couldn't connect to host' in /opt/kaltura/app/batch/client/KalturaClientBase.php:362
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(1131): KalturaClientBase->doQueue()
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 894
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(634): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 894
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(634): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 362
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'couldn't connect to host' in /opt/kaltura/app/batch/client/KalturaClientBase.php:362
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(1116): KalturaClientBase->doQueue()
--
==> /opt/kaltura/log/batch/synchronizedistribution-0-2016-01-12.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaPlugins/KalturaContentDistributionClientPlugin.php(2804): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 894
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal server error occurred' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4124): KalturaClientBase->throwExceptionIfError(Array)
--
2016-01-12 10:00:13 [0.000670] [::1] [60333554] [15] [API] [KalturaStatement->execute] DEBUG: /* kaltura.babyflix.net[60333554][propel] */ INSERT INTO scheduler (`ID`,`CREATED_AT`,`UPDATED_AT`,`CONFIGURED_ID`,`NAME`,`DESCRIPTION`,`LAST_STATUS`,`HOST`) VALUES (NULL,'2016-01-12 10:00:13','2016-01-12 10:00:13','99524','kaltura.babyflix.net','','2016-01-12 10:00:13','kaltura.babyflix.net')
2016-01-12 10:00:13 [0.000419] [::1] [60333554] [16] [API] [BasePeer::doInsert] ERR: exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'statuses' doesn't have a default value' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(408): KalturaLog::err('SQLSTATE[HY000]...')
--
2016-01-12 10:00:13 [0.000381] [::1] [60333554] [17] [API] [KalturaFrontController->getExceptionObject] ALERT: exception 'PropelException' with message 'Unable to execute INSERT statement. [wrapped: SQLSTATE[HY000]: General error: 1364 Field 'statuses' doesn't have a default value]' in /opt/kaltura/app/vendor/propel/util/BasePeer.php:299
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/om/BaseSchedulerPeer.php(762): BasePeer::doInsert(Object(Criteria), Object(KalturaPDO))
--
==> /opt/kaltura/log/batch/kschedulehelper-0-2016-01-12.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(634): KalturaClientBase->throwExceptionIfError(Array)

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by Abhimanyu008** [comment]
I have done the mysqlcheck and it seems fine to me. I am thinking the error is related to the kaltura batch process scheduler as worker_configured_id is null error is thrown on console for scheduler_config table in insert statement whenever i try to upload a file. I have also truncate dscheduler, scheduler_config, scheduler_status , scheduler_worker tables ( after taking the backup) and run the kaltura_batch_config.sh as well as restart the kaltura-batch process but it neither generate the table nor the restart thrown any error. both kaltura_batch_config.sh and kaltura-batch service run successfully. But the error remains the same. I have also found that earlier I had no category available in kmc but when I run shpinx reindex it gives me all the category start appearing in KMC as well as there was metadata entry for all the unsuccessfull upload. When I delete these metadata then status appeared to deleted but they were still in kmc. I think it has an issue with database entry of scheduler.

**Comment by tan-tan-kanarek** [comment]
The scheduler (top level configuration) doesn't have a configured worker id.
This column should be nullable.

**Comment by jessp01** [comment]
Hi,

You have a lot of different issues here, including:
PHP Warning: file_put_contents(): Only 0 of 5 bytes written, possibly out of free disk space in /opt/kaltura/app/batch/scheduler/KScheduleHelperManager.class.php on line 199

Which would indicate you are still having space issues and 
[Tue Jan 12 15:46:29 2016] [error] [client 199.30.25.144] PHP Warning: rename(/tmp/0_s8d16nghCAIVT2,/opt/kaltura/app/cache//html5/v2.37.1/iframe/0/0_s8d16ngh): Permission denied in /opt/kaltura/web/html5/html5lib/v2.37.1/modules/KalturaSupport/Cache/kFileSystemCacheWrapper.php on line 156, referer: http://www.babyflix.net/

Which means that /opt/kaltura/app/cache/ is not writeable for both the 'apache' and 'kaltura' users.

My guess would be you deleted the whole cache dir cause you ran out of space, that is not good because the installation creates it and sub directories under it with specific permissions.
When you run out of space, you need to do:
\# find /opt/kaltura/app/cache -type f -exec rm {} \;
instead.

That would only remove files and not dirs.

I suggest you do a yum reinstall kaltura-base in order to recreate the directories correctly and then re-run the kaltura-config-all.sh script.

Neither should cause any data loss but before you do so, make sure you backup the DB and config files just in case.

Since we want to use the github issue section for bug reporting exclusively, and this is not a general bug report, I am closing the issue but feel free to post a follow up on forum.kaltura.org.

**Comment by infra-oodles** [comment]
Hi, The following error in kaltura mysql DB  was due to strict mode in sql.

>  'PropelException' with message 'Unable to execute INSERT statement. [wrapped: SQLSTATE[HY000]: General error: 1364 Field 'priority' doesn't have a default value]' 

Somehow the SQL server was in running in Strict mode. After removing the strict mode, kaltura is now working fine.

To change the SQL mode without restarting Mysql, fire the command in mysql client
`SET GLOBAL sql_mode = "";  `

To make the changes persistent add following line in my.cnf in [mysqld] section

> [mysqld]
> sql_mode = ""

Then, Restart the mysql.

Hope this will help!
