### ISSUE TITLE
KALTURA 11.5 TEST CONSOLE UPLOAD ISSUE

### ISSUE THREAD

**Issue by infra-oodles** [kaltura/server#3708]
Hi,

I have updated my kaltura-server version from 11.2 to 11.5, and now i am unable to upload the files through APIs, Please help me .

I am using CentOS release 6.7 (Final).
Mysql version-  14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

And below are my kaltura packages versions ---

kaltura-release-11.2.0-1.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-html5lib-v2.37.1-2.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-batch-11.2.0-1.noarch
kaltura-server-11.5.0-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-libass-0.9.11-2.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-postinst-1.0.30-2.noarch
kaltura-base-11.2.0-12.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kupload-1.0.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-html5-studio-v2.0.1-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-librtmp-2.3-2.x86_64
kaltura-front-11.2.0-1.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-monit-5.13-1.x86_64
kaltura-kdp-v2.7.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kmc-v5.39.11-3.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-nginx-1.8.0-9.x86_64
kaltura-dwh-9.5.0-2.noarch

I am able to upload files from kaltura upload button in kmc, but while uploading through admin console > developers > Test Console, when uploading a file it gives following result-
<xml>
    <result>1011452751685.6159_u8ygq3calw80wo04cc04.jpeg</result>
    <executionTime>0.096429109573364</executionTime>
</xml>
 
But file is not uploading. and showing in content list, as well as not generating metadata. whereas using test console to create metadata its working fine. and other APIs from test console are also working fine.

**Comment by kaltura-hooks** [comment]
Hi @infra-oodles,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by infra-oodles** [comment]
Hi Kaltura-hooks
* Yes the issue is consistent and across the platform

* I'm using self-hosted, RPM install

* rpm -qa "*kaltura*"  -
kaltura-release-11.2.0-1.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-html5lib-v2.37.1-2.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-batch-11.2.0-1.noarch
kaltura-server-11.5.0-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-libass-0.9.11-2.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-postinst-1.0.30-2.noarch
kaltura-base-11.2.0-12.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kupload-1.0.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-html5-studio-v2.0.1-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-librtmp-2.3-2.x86_64
kaltura-front-11.2.0-1.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-monit-5.13-1.x86_64
kaltura-kdp-v2.7.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kmc-v5.39.11-3.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-nginx-1.8.0-9.x86_64
kaltura-dwh-9.5.0-2.noarch

* mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

*It is single all in one server.

# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Thu Jan 14 04:30:48 2016] [error] [client 222.186.30.78] File does not exist: /opt/kaltura/app/alpha/web/login.action
[Thu Jan 14 05:24:31 2016] [error] [client 80.82.64.68] File does not exist: /opt/kaltura/app/alpha/web/public
[Thu Jan 14 05:36:51 2016] [error] [client 208.52.161.177] File does not exist: /opt/kaltura/app/alpha/web/myadmin


--
            [tmp_name] => /opt/kaltura/web/tmp/phpXE4FFx
            [error] => 0
            [size] => 693897
--
            [tmp_name] => /opt/kaltura/web/tmp/phpXE4FFx
            [error] => 0
            [size] => 693897
--
    [tmp_name] => /opt/kaltura/web/tmp/phpXE4FFx
    [error] => 0
    [size] => 693897
--
    [tmp_name] => /opt/kaltura/web/tmp/phpXE4FFx
    [error] => 0
    [size] => 693897

**Comment by jessp01** [comment]
What happens when you run:
\# /opt/kaltura/bin/kaltura-sanity.sh
or use the script it uses for upload directly, i.e:
\# php /opt/kaltura/bin/upload_test.php <service_url> <partnerid> <secret> </path/to/asset>

**Comment by infra-oodles** [comment]
thanks for your reply jessp01.
i have resolved this issue. I was uploading it wrongly, without creating metadata so it was not uploading my files.
