### ISSUE TITLE
Configuration templates for logrotate contain 'su root kaltura' which is not a recognised directive on CentOS6

### ISSUE THREAD

**Issue by wzur** [kaltura/server#3872]
Hi @jessp01,

All files in logrotate folder contain `su root kaltura`, which is not recognised by logrotate on CentOS6.
This is a minor issue, as logrotate quite happily ignores them

Waldemar

**Comment by jessp01** [comment]
Hi @wzur,

Well aware, thank you:)
Alas, logrotate does not provide means for checking its version from the config files and this configuration is mandatory for newer logrotate versions so, there's not much I can do about it but close the issue.
Nonetheless, thank you for taking the time to report it.

**Comment by wzur** [comment]
Oh well - you could always detect the version of CentOS from the post installation script and process logrotate templates slightly differently.

In the meantime - I'll try to search tickets first, before creating a new one...

**Comment by jessp01** [comment]
If it were actually hurting something, I would have:) but considering it 
only emits a warning, I did not feel it is worth it.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]
