### ISSUE TITLE
admin console & add new publisher wrong email validation

### ISSUE THREAD

**Issue by kkretsch** [kaltura/server#4411]
The current (11.16) admin console doesn't allow me to create a new publisher with a ".email" tld. I don't think it is neither wise nor possible to keep a list of allowed top lovel domains. Just a check for one or more dots in the middle of the domain part should be enough.

.email' appears to be a DNS hostname but cannot match TLD against known list

**Comment by kaltura-hooks** [comment]
Hi @kkretsch,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by kkretsch** [comment]
Some more info:

# rpm -qa \*kaltura\*
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-libfaac-1.26-1.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-dwh-11.3.0-1.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-front-11.16.0-1.noarch
kaltura-nginx-1.8.1-5.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-libass-0.9.11-2.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-x264-0.140-2.20140104.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-postinst-1.0.31-11.noarch
kaltura-batch-11.16.0-1.noarch
kaltura-html5lib-v2.44-1.noarch
kaltura-kmc-v5.40.2-2.noarch
kaltura-release-11.16.0-1.noarch
kaltura-monit-5.13-1.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-red5-1.0.6-1.x86_64
kaltura-html5-studio-v2.0.5-1.noarch
kaltura-base-11.16.0-9.noarch
kaltura-server-11.16.0-1.noarch

Your MySQL Server version: 5.1.73 Source distribution

# uname -a
Linux 3c053821b677 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 x86_64 x86_64 GNU/Linux

Based on the docker install howto and updated after install.

**Comment by kkretsch** [comment]
I think the error comes from the file /opt/kaltura/app/vendor/ZendFramework/library/Zend/Validate/Hostname.php where it says:

` /**
     * Array of valid top-level-domains
     *
     * @see ftp://data.iana.org/TLD/tlds-alpha-by-domain.txt  List of all TLDs by domain
     * @see http://www.iana.org/domains/root/db/ Official list of supported TLDs
     * @var array
     */
    protected $_validTlds = array(
        'ac', 'ad', 'ae', 'aero', 'af', 'ag', 'ai', 'al', 'am', 'an', 'ao', 'aq', 'ar', 'arpa',
        'as', 'asia', 'at', 'au', 'aw', 'ax', 'az', 'ba', 'bb', 'bd', 'be', 'bf', 'bg', 'bh', 'bi',
        'biz', 'bj', 'bm', 'bn', 'bo', 'br', 'bs', 'bt', 'bv', 'bw', 'by', 'bz', 'ca', 'cat', 'cc',
        'cd', 'cf', 'cg', 'ch', 'ci', 'ck', 'cl', 'cm', 'cn', 'co', 'com', 'coop', 'cr', 'cu',
        'cv', 'cx', 'cy', 'cz', 'de', 'dj', 'dk', 'dm', 'do', 'dz', 'ec', 'edu', 'ee', 'eg', 'er',
        'es', 'et', 'eu', 'fi', 'fj', 'fk', 'fm', 'fo', 'fr', 'ga', 'gb', 'gd', 'ge', 'gf', 'gg',
        'gh', 'gi', 'gl', 'gm', 'gn', 'gov', 'gp', 'gq', 'gr', 'gs', 'gt', 'gu', 'gw', 'gy', 'hk',
        'hm', 'hn', 'hr', 'ht', 'hu', 'id', 'ie', 'il', 'im', 'in', 'info', 'int', 'io', 'iq',
        'ir', 'is', 'it', 'je', 'jm', 'jo', 'jobs', 'jp', 'ke', 'kg', 'kh', 'ki', 'km', 'kn', 'kp',
        'kr', 'kw', 'ky', 'kz', 'la', 'lb', 'lc', 'li', 'lk', 'lr', 'ls', 'lt', 'lu', 'lv', 'ly',
        'ma', 'mc', 'md', 'me', 'mg', 'mh', 'mil', 'mk', 'ml', 'mm', 'mn', 'mo', 'mobi', 'mp',
        'mq', 'mr', 'ms', 'mt', 'mu', 'museum', 'mv', 'mw', 'mx', 'my', 'mz', 'na', 'name', 'nc',
        'ne', 'net', 'nf', 'ng', 'ni', 'nl', 'no', 'np', 'nr', 'nu', 'nz', 'om', 'org', 'pa', 'pe',
        'pf', 'pg', 'ph', 'pk', 'pl', 'pm', 'pn', 'pr', 'pro', 'ps', 'pt', 'pw', 'py', 'qa', 're',
        'ro', 'rs', 'ru', 'rw', 'sa', 'sb', 'sc', 'sd', 'se', 'sg', 'sh', 'si', 'sj', 'sk', 'sl',
        'sm', 'sn', 'so', 'sr', 'st', 'su', 'sv', 'sy', 'sz', 'tc', 'td', 'tel', 'tf', 'tg', 'th',
        'tj', 'tk', 'tl', 'tm', 'tn', 'to', 'tp', 'tr', 'travel', 'tt', 'tv', 'tw', 'tz', 'ua',
        'ug', 'uk', 'um', 'us', 'uy', 'uz', 'va', 'vc', 've', 'vg', 'vi', 'vn', 'vu', 'wf', 'ws',
        'ye', 'yt', 'yu', 'za', 'zm', 'zw'
    );`

The idea to keep a static list of valid tld is a now-go nowadays.

**Comment by jessp01** [comment]
Hi @kkretsch,

Can you please verify adding 'tld' to this array works and then make a pull request?

Thanks,

**Comment by jessp01** [comment]
Hi @kkretsch,

Kaltura CE 12.13.0 was just released. This is resolved there. Thanks for reporting.
