### ISSUE TITLE
kaltura-sphinx fails to set up autostart 

### ISSUE THREAD

**Issue by Ivorforce** [kaltura/server#4453]
Whenever I reboot my kaltura server, kaltura-sphinx has to be started manually (service kaltura-sphinx start). To fix the problem, I tried to enable it for autostart, but that command fails with 

update-rc.d: error: kaltura-sphinx Default-Start contains no runlevels, aborting.

I also tried purging and reinstalling kaltura-sphinx entirely.
The full log:
https://gist.github.com/Ivorforce/3eb8449495cfbf3412c6a6c1322d02a4

Package list:

root@tuedfvw-kaltura:~# dpkg -l "kaltura-*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  kaltura-base   11.17.0-2    all          Kaltura Open Source Video Platfor
ii  kaltura-batch  11.17.0-1    all          Kaltura Open Source Video Platfor
ii  kaltura-clipap 1.3-1+b2     all          Kaltura Video Presentations Manag
ii  kaltura-db     11.4.0-1     all          Kaltura Open Source Video Platfor
ii  kaltura-dwh    10.10.0-2+b1 amd64        Kaltura Open Source Video Platfor
ii  kaltura-ffmpeg 2.7.2-1+b6   amd64        
ii  kaltura-ffmpeg 2.1.3-1      amd64        
ii  kaltura-front  11.17.0-1    all          Kaltura Open Source Video Platfor
ii  kaltura-html5- 2.0.5-1      all          Kaltura Open Source Video Platfor
ii  kaltura-html5l 2.44-1+b1    all          Kaltura Open Source Video Platfor
ii  kaltura-kclip  1.1.2.1-1    all          Kaltura Video Presentations Manag
ii  kaltura-kcw    2.2.4-1+b3   all          Kalture Contribution Wizard
ii  kaltura-kdp    2.7.0-1      all          Kaltura Dynamic Player
ii  kaltura-kdp3   3.9.9-1+b3   amd64        Kaltura Dynamic Player
ii  kaltura-kdp3wr 37-1         all          KDP3 Wrapper
ii  kaltura-kdpwra 11-1         all          KDP Wrapper
ii  kaltura-kmc    5.40.2-2+b2  all          Kaltura Management Console
ii  kaltura-krecor 1.7-1        all          Kaltura kRecord - used for record
ii  kaltura-kuploa 1.2.16-1     all          Kaltura kupload widget
ii  kaltura-libapa 7.0.0-9      amd64        server-side, HTML-embedded script
ii  kaltura-nginx  1.8.1-3+b2   amd64        Nginx web/proxy server - for Kalt
ii  kaltura-pentah 4.2.1+b2     amd64        Pentaho Open Source Data Integrat
ii  kaltura-php7   7.0.0-9      all          server-side, HTML-embedded script
ii  kaltura-php7-a 5.1.0-3      amd64        APC User Cache for PHP 7
ii  kaltura-php7-c 7.0.0-9      amd64        command-line interpreter for the 
ii  kaltura-php7-c 7.0.0-9      amd64        Common files for packages built f
ii  kaltura-php7-c 7.0.0-9      amd64        CURL module for kaltura-php7
ii  kaltura-php7-g 7.0.0-9      amd64        GD module for kaltura-php7
ii  kaltura-php7-g 7.0.0-9      amd64        GMP module for kaltura-php7
ii  kaltura-php7-m 7.0.0-9      amd64        MCrypt module for kaltura-php7
ii  kaltura-php7-m 3.0.9-2      amd64        memcache extension module for PHP
ii  kaltura-php7-m 7.0.0-9      amd64        MySQL module for kaltura-php7
un  kaltura-php7-m <none>       <none>       (no description available)
un  kaltura-php7-m <none>       <none>       (no description available)
ii  kaltura-php7-o 7.0.0-9      amd64        Opcache module for kaltura-php7
ii  kaltura-php7-s 0.12-2       amd64        PHP Bindings for libssh2
ii  kaltura-php7-x 7.0.0-9      amd64        XSL module for kaltura-php7
ii  kaltura-postin 1.0.31-1+b3  all          Kaltura Open Source Video Platfor
ii  kaltura-red5   1.0.0-1+b2   amd64        Kaltura Open Source Video Platfor
ii  kaltura-sphinx 2.2.1-3+b5   amd64        Sphinx full-text search server - 
ii  kaltura-widget 10.9.0-1+b4  all          Kaltura Open Source Video Platfor

MySQL: mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3
MySQLd: mysqld  Ver 5.5.49-0+deb8u1 for debian-linux-gnu on x86_64 ((Debian))
The server is a virtual debian (Debian GNU/Linux 8.5 (jessie)) machine in a cluster.

**Comment by kaltura-hooks** [comment]
Hi @Ivorforce,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by Ivorforce** [comment]
Updated with mysql versions, installed packages and cluster info.

**Comment by jessp01** [comment]
Hi @Ivorforce,
Pardon the delay in response. In the future, please post such issues on https://github.com/kaltura/platform-install-packages/ instead.

I've just committed a fix for it, see: https://github.com/kaltura/platform-install-packages/commit/e056d2c069eb808814e2f18fcd7a5d12fa87f9b8#diff-7a8e32f830896cc0f935badc7773ccd5L12

It will become the stable version on Oct 23rd but go ahead and edit /etc/init.d/kaltura-sphinx manually for now.

Thanks for reporting,
