### ISSUE TITLE
the note of "replace the tokens"

### ISSUE THREAD

**Issue by d4wner** [kaltura/server#6691]
Well, I've rename the admin.ini, then the index.php remind me to replace the tokens.

I just download the zip file, and put it into the webroot.

But I don't find where're the tokens which is noted in the "admin_console\web\index.php",

Could the author tell me where and how to replace them?

Maybe you could give me some notes about it ,sir...

Thx~

**Comment by jessp01** [comment]
Hi @d4wner,

What exactly are you trying to accomplish? There is no need to replace tokens manually. If you're looking to deploy a Kaltura Server on your self hosted ENV, we provide RPM and deb packages, see here:
https://github.com/kaltura/platform-install-packages/#documentation-and-guides

For additional general questions, please post at forum.kaltura.org.
We'd like to use the "issues" section for bug reporting only.

Thanks,
