### ISSUE TITLE
Error of Kaltura after a reboot 

### ISSUE THREAD

**Issue by guidtz** [kaltura/server#8017]
- [ ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) or submitted to the support team in the form of a ticket 

## Bug report
After a reboot of the server, when we upload a video, the videos doesn't appear in content and in log we have this : 
```
2019-01-14 22:10:27 [192.168.44.1] [514548972] [API] [KalturaFrontController->getExceptionObject] ERR: exception 'KalturaAPIException' with message 'Notification for entry id "0_epzwjuco" not found' in /opt/kaltura/app/api_v3/services/NotificationService.php:34
Stack trace:
#0 [internal function]: NotificationService->getClientNotificationAction('0_epzwjuco', 1)
#1 /opt/kaltura/app/api_v3/lib/KalturaServiceReflector.php(276): call_user_func_array(Array, Array)
#2 /opt/kaltura/app/api_v3/lib/KalturaDispatcher.php(120): KalturaServiceReflector->invoke('getClientNotifi...', Array)
#3 /opt/kaltura/app/api_v3/lib/KalturaFrontController.php(201): KalturaDispatcher->dispatch('notification', 'getClientNotifi...', Array)
#4 /opt/kaltura/app/api_v3/lib/KalturaFrontController.php(51): KalturaFrontController->handleMultiRequest()
#5 /opt/kaltura/app/api_v3/web/index.php(19): KalturaFrontController->run()
#6 {main}
```
How to debug this problem ?

## Kaltura ENV
*Please fill out this section if you are hosting the Kaltura platform on your own servers [as opposed to using Kaltura SaaS]. In the event of SaaS, the below should be deleted.*

**Relevant errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**
Centos 6

**Are you using the RPM or deb packages?**
From Souce (installed by another person)

**Is this an all in one instance [single server] or a cluster?**
- [ ] All in one

**If applicable, please provide the MySQL version:**
MySQL 5.5

Thanks for you're help

**Comment by jessp01** [comment]
Hello @guidtz,

Is your Sphinx running? if not, please start it:
```sh
# /etc/init.d/kaltura-sphinx start
```

Then call `/etc/init.d/kaltura-sphinx status` to ensure it is running, if it isn't, check /opt/kaltura/log/sphinx/kaltura_sphinx_searchd.log to understand why.

If it is running and you still don't see the content, try to reindex, for that, see:
https://forum.kaltura.org/t/we-cannot-get-the-list-of-category-from-the-kaltura-ce-v14-4-0/8400/2

**Comment by guidtz** [comment]
Ok It's seems to works after a restart of alls servers. I continue my testings
