### ISSUE TITLE
A bug with analytics?

### ISSUE THREAD

**Issue by mahameed** [kaltura/server#9145]
https://forum.kaltura.org/t/kmcng-analytics-errors-in-all-graphics/9552

We’re having similar issue with out analytics. Analytics page has multiple popups that say " Error Internal server error occurred". Here’s our output from the following commands:

```
# rpm -q kaltura-base kaltura-html5-analytics
kaltura-base-14.19.0-12.noarch
kaltura-html5-analytics-v0.2-2.noarch
```
```
# grep kmc_analytics_version /opt/kaltura/app/configurations/base.ini
kmc_analytics_version** = v0.2
```
Please help. Thanks.

**Comment by jessp01** [comment]
Hello,

First, please upgrade to the latest version (15.14.0).
If, following that, the issue persists, take a look at https://forum.kaltura.org/t/kmcng-analytics-errors-in-ui/10260/2 and post your findings on the forum.

Thanks,
