### ISSUE TITLE
Child entries showing up in KMC Search

### ISSUE THREAD

**Issue by jbrule** [kaltura/server#9417]
## Bug report
**Please provide a detailed description of the issue and the steps to reproduce:**

When searching by entryId child assets are now being returned in the KMC. This is common when using Kaltura Capture

![Screen Shot 2020-05-15 at 1 02 25 PM](https://user-images.githubusercontent.com/765798/82081683-5d2d1b80-96ac-11ea-8643-3631fbb8e4ed.png)

```
{
  "mediaType": 1,
  "conversionQuality": 6167171,
  "sourceType": "37",
  "plays": 0,
  "views": 0,
  "width": 1280,
  "height": 720,
  "duration": 271,
  "msDuration": 271000,
  "id": "1_hlr4gsaz",
  "name": "Kaltura Capture recording - April 27th 2020, 3:42:53 pm",
  "description": "5020 Intro Part 2 (2nd take)",
   ...
  "parentEntryId": "1_868qgs4e",
   ...
}
```

## Kaltura ENV
Kaltura SaaS

**Comment by jessp01** [comment]
Hello,

This is because the related entry (ID 1_hlr4gsaz in your case) has the displayInSearch member (on the KalturaMediaEntry object) set to -1. This is actually by design.

Cheers,

**Comment by jbrule** [comment]
You've confused me. Doesn't displayInSearch = -1 mean it shouldn't be returned?
