### ISSUE TITLE
When I add users using API (user.add), the users are not showing up in KMS user management. But when I use user.get api I am able to find the user. Help!

### ISSUE THREAD

**Issue by lucifer119** [kaltura/server#9479]
Hey, when I use an api like user.add the users are not shown in Kaltura User management (/admin/user-list). Not the admin one. Can you help me out

**Comment by jessp01** [comment]
Hello,

From the URI you quoted (`/admin/user-list`), I deduce you're asking about KMS (Kaltura MediaSpace). If so, this really does not pertain to this repo. See https://forum.kaltura.org/t/not-able-to-set-password-for-end-user/4753/10
For follow up questions, please post on the forum.

Thanks,
