### ISSUE TITLE
Partner/Publisher Urls

### ISSUE THREAD

**Issue by chrisschaub** [kaltura/server#971]
You can set custom urls per partner for delivery, cdn and stats. These urls don't seem to get reflected in LocalSettings.php. One hack I've done to LocalSettings.php is to change ...
```
$wgKalturaServiceUrl = wgGetUrl('cdn_api_host');
```
to
```
$wgKalturaServiceUrl = 'http://'.$_SERVER['HTTP_HOST'];
```

which will get the host of the request which seems to fix the partner urls using the standard embed method. But, using the share plugin, the embed url generates code that doesn't honor partner urls in the source code. I think the problem is in this file ...

./app/alpha/apps/kaltura/modules/extwidget/templates/previewSuccess.php
```
<meta property="og:video" content="<?php echo $swfSecureUrl; ?>" />
```
that variable doesn't seem to contain the custom partner url.

Would it be possible to honor  partner urls wherever they can be used? That way you can have one media server with many partners, the data hosted up on a cdn like Amazon S3 Cloudfront, and the urls only give away "partner" urls.

**Comment by jessp01** [comment]
Closing since this is very old and was already fixed. If there are still issues with recent versions, please open an issue at https://github.com/kaltura/mwembed/
